import { useEntityStore } from '../store/useEntityStore';
import { useProjectStore } from '../store/useProjectStore';
import { useHistoryStore } from '../store/useHistoryStore';
import type { Entity, Column, Feature, Priority, Estimate, Milestone } from '../types';
import { createId } from './id';

export interface BackupData {
  version: number;
  exportedAt: string;
  projectName: string;
  entities: ReturnType<typeof useEntityStore.getState>['entities'];
  meta: ReturnType<typeof useProjectStore.getState>['meta'];
  features: ReturnType<typeof useProjectStore.getState>['features'];
  milestones: ReturnType<typeof useProjectStore.getState>['milestones'];
  scope: ReturnType<typeof useProjectStore.getState>['scope'];
  endpoints: ReturnType<typeof useProjectStore.getState>['endpoints'];
}

export function backupProject(): void {
  const es = useEntityStore.getState();
  const ps = useProjectStore.getState();

  const data: BackupData = {
    version: 1,
    exportedAt: new Date().toISOString(),
    projectName: ps.meta.name || 'Untitled Project',
    entities: es.entities,
    meta: ps.meta,
    features: ps.features,
    milestones: ps.milestones,
    scope: ps.scope,
    endpoints: ps.endpoints,
  };

  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(ps.meta.name || 'surplan-project').replace(/\s+/g, '-').toLowerCase()}-backup.json`;
  a.click();
  URL.revokeObjectURL(url);
}

export function restoreProject(file: File): Promise<{ success: boolean; message: string }> {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const data = JSON.parse(e.target?.result as string) as BackupData;

        if (!data.version || !data.entities || !data.meta) {
          resolve({ success: false, message: 'Invalid backup file format' });
          return;
        }

        useHistoryStore.setState({ isReverting: true, past: [], future: [] });

        useEntityStore.setState({ entities: data.entities ?? [] });
        useProjectStore.setState({
          meta: data.meta,
          features: data.features ?? [],
          milestones: data.milestones ?? [],
          scope: data.scope ?? [],
          endpoints: data.endpoints ?? [],
        });

        Promise.resolve().then(() =>
          useHistoryStore.setState({ isReverting: false })
        );

        resolve({ success: true, message: `Restored "${data.meta.name || 'project'}" from backup` });
      } catch {
        resolve({ success: false, message: 'Failed to parse backup file' });
      }
    };
    reader.readAsText(file);
  });
}

function entityToMarkdownTable(entity: Entity): string {
  const rows = entity.columns.map((c) => {
    const flags = [
      c.primaryKey ? 'PK' : '',
      c.nullable ? 'NULL' : 'NOT NULL',
      c.unique ? 'UNIQUE' : '',
      c.indexed && !c.primaryKey ? 'INDEX' : '',
      c.defaultValue ? `DEFAULT ${c.defaultValue}` : '',
      c.references ? `FK → ${c.references.entityName}.${c.references.columnName}` : '',
      c.check?.trim() ? `CHECK (${c.check.trim()})` : '',
    ].filter(Boolean).join(', ');
    return `| ${c.name} | ${c.dataType} | ${flags} | ${c.note || ''} |`;
  });
  return [
    `### ${entity.name}`,
    entity.description ? `\n*${entity.description}*\n` : '',
    '',
    '| Column | Type | Constraints | Note |',
    '|--------|------|-------------|------|',
    ...rows,
  ].join('\n');
}

export function exportProjectMarkdown(): void {
  const es = useEntityStore.getState();
  const ps = useProjectStore.getState();
  const { meta, features, milestones, scope, endpoints } = ps;
  const { entities } = es;

  const lines: string[] = [];

  // Header
  lines.push(`# ${meta.name || 'Untitled Project'}`);
  lines.push('');
  if (meta.description) {
    lines.push(meta.description);
    lines.push('');
  }
  lines.push(`> *Generated by surplan · ${new Date().toLocaleDateString()}*`);
  lines.push('');

  // Tech Stack
  if (meta.techStackNotes) {
    lines.push('## Tech Stack');
    lines.push('');
    lines.push(meta.techStackNotes);
    lines.push('');
  }

  // Scope
  const inScope = scope.filter((s) => s.inScope);
  const outScope = scope.filter((s) => !s.inScope);
  if (scope.length > 0) {
    lines.push('## Scope');
    lines.push('');
    if (inScope.length > 0) {
      lines.push('### In Scope');
      inScope.forEach((s) => lines.push(`- ${s.text}`));
      lines.push('');
    }
    if (outScope.length > 0) {
      lines.push('### Out of Scope');
      outScope.forEach((s) => lines.push(`- ${s.text}`));
      lines.push('');
    }
  }

  // Features
  if (features.length > 0) {
    lines.push('## Features');
    lines.push('');

    const doneTotal = features.filter((f) => f.done).length;
    lines.push(`*${doneTotal}/${features.length} complete*`);
    lines.push('');

    // Group by milestone
    const groups = [
      ...milestones.map((m) => ({
        label: m.name,
        items: features.filter((f) => f.milestone === m.id),
      })),
      {
        label: 'Backlog',
        items: features.filter((f) => !f.milestone),
      },
    ].filter((g) => g.items.length > 0);

    for (const group of groups) {
      const done = group.items.filter((f) => f.done).length;
      lines.push(`### ${group.label} (${done}/${group.items.length})`);
      lines.push('');
      for (const f of group.items) {
        const check = f.done ? '[x]' : f.inProgress ? '[-]' : '[ ]';
        const priority = f.priority !== 'medium' ? ` *(${f.priority})*` : '';
        const assigneeMd = f.assignee ? ` @${f.assignee}` : '';
        const dueMd = f.dueDate ? ` 📅 ${f.dueDate}` : '';
        const urlMd = f.url ? ` [🔗](${f.url})` : '';
        lines.push(`- ${check} **${f.title}**${priority}${assigneeMd}${dueMd}${urlMd}`);
        if (f.description) lines.push(`  > ${f.description}`);
        if (f.notes) lines.push(`  *Notes: ${f.notes.replace(/\n/g, ' ')}*`);
        if (f.checklist?.length) {
          f.checklist.forEach((c) => lines.push(`  - [${c.done ? 'x' : ' '}] ${c.text}`));
        }
      }
      lines.push('');
    }
  }

  // API Endpoints
  if (endpoints.length > 0) {
    lines.push('## API Endpoints');
    lines.push('');

    // Group by tag
    const tags = Array.from(new Set(endpoints.map((e) => e.tag || 'General')));
    for (const tag of tags) {
      const tagEps = endpoints.filter((e) => (e.tag || 'General') === tag);
      lines.push(`### ${tag}`);
      lines.push('');
      for (const ep of tagEps) {
        let line = `- \`${ep.method}\` \`${ep.path}\`${ep.description ? ` — ${ep.description}` : ''}`;
        if (ep.queryParams?.trim()) line += ` *(query: ${ep.queryParams})*`;
        if (ep.statusCodes?.trim()) line += ` → ${ep.statusCodes}`;
        lines.push(line);
        if (ep.notes?.trim()) lines.push(`  > ${ep.notes}`);
      }
      lines.push('');
    }
  }

  // Data Model
  if (entities.length > 0) {
    lines.push('## Data Model');
    lines.push('');
    for (const entity of entities) {
      lines.push(entityToMarkdownTable(entity));
      lines.push('');
    }
  }

  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(meta.name || 'surplan-project').replace(/\s+/g, '-').toLowerCase()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Features CSV Export ───────────────────────────────────────────────────────

export function exportFeaturesCSV(): void {
  const ps = useProjectStore.getState();
  const es = useEntityStore.getState();
  const { features, milestones, meta } = ps;
  const { entities } = es;

  const milestoneMap = new Map(milestones.map((m) => [m.id, m.name]));
  const entityMap = new Map(entities.map((e) => [e.id, e.name]));

  const escape = (val: string) => `"${val.replace(/"/g, '""')}"`;

  const header = ['Title', 'Status', 'Kind', 'Priority', 'Estimate', 'Value', 'Sprint', 'Start Date', 'Due Date', 'Completed At', 'Milestone', 'Tags', 'Entity Refs', 'Notes', 'URL', 'Assignee', 'Checklist'];
  const rows = features.map((f) => [
    escape(f.title),
    f.done ? 'done' : f.inProgress ? 'in-progress' : 'todo',
    f.kind ?? 'feature',
    f.priority,
    f.estimate ?? '',
    f.value ?? '',
    escape(f.sprint ?? ''),
    f.startDate ?? '',
    f.dueDate ?? '',
    f.completedAt ?? '',
    escape(f.milestone ? (milestoneMap.get(f.milestone) ?? f.milestone) : ''),
    escape((f.tags ?? []).join(', ')),
    escape((f.entityRefs ?? []).map((id) => entityMap.get(id) ?? id).join(', ')),
    escape(f.notes ?? ''),
    escape(f.url ?? ''),
    escape(f.assignee ?? ''),
    escape((f.checklist ?? []).map((c) => `[${c.done ? 'x' : ' '}] ${c.text}`).join(' | ')),
  ]);

  const csv = [header.join(','), ...rows.map((r) => r.join(','))].join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(meta.name || 'surplan-project').replace(/\s+/g, '-').toLowerCase()}-features.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Feature CSV Import ─────────────────────────────────────────────────────────

const IMPORT_MILESTONE_COLORS = [
  '#6366f1', '#8b5cf6', '#10b981', '#f59e0b', '#ef4444', '#06b6d4', '#ec4899', '#64748b',
];

/** Parse a single CSV line respecting quoted fields */
function parseCSVLine(line: string): string[] {
  const result: string[] = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') { cur += '"'; i++; }
      else inQuotes = !inQuotes;
    } else if (ch === ',' && !inQuotes) {
      result.push(cur); cur = '';
    } else {
      cur += ch;
    }
  }
  result.push(cur);
  return result;
}

export function importFeaturesCSV(file: File): Promise<{ success: boolean; message: string; count?: number }> {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const text = e.target?.result as string;
        const lines = text.split('\n').map((l) => l.trim()).filter(Boolean);
        if (lines.length < 2) {
          resolve({ success: false, message: 'CSV has no data rows' });
          return;
        }

        const headers = parseCSVLine(lines[0]).map((h) =>
          h.toLowerCase().replace(/\s+/g, '').replace(/[^a-z]/g, '')
        );
        const getCol = (row: string[], name: string) => {
          const idx = headers.indexOf(name);
          return idx >= 0 ? (row[idx]?.trim() ?? '') : '';
        };

        const ps = useProjectStore.getState();
        const es = useEntityStore.getState();

        const milestoneByName = new Map(ps.milestones.map((m) => [m.name.toLowerCase(), m.id]));
        const entityByName = new Map(es.entities.map((e) => [e.name.toLowerCase(), e.id]));

        const newMilestones: Milestone[] = [];
        const getMilestoneId = (name: string): string => {
          if (!name) return '';
          const lower = name.toLowerCase();
          if (milestoneByName.has(lower)) return milestoneByName.get(lower)!;
          const already = newMilestones.find((m) => m.name.toLowerCase() === lower);
          if (already) return already.id;
          const id = createId();
          const color = IMPORT_MILESTONE_COLORS[(ps.milestones.length + newMilestones.length) % IMPORT_MILESTONE_COLORS.length];
          newMilestones.push({ id, name, description: '', color });
          milestoneByName.set(lower, id);
          return id;
        };

        const VALID_PRIORITIES = new Set<Priority>(['critical', 'high', 'medium', 'low', 'nice-to-have']);
        const VALID_ESTIMATES = new Set<Estimate>(['', '1', '2', '3', '5', '8', '13', '?']);

        const newFeatures: Feature[] = [];
        for (let i = 1; i < lines.length; i++) {
          const row = parseCSVLine(lines[i]);
          const title = getCol(row, 'title');
          if (!title) continue;

          const statusRaw = getCol(row, 'status').toLowerCase();
          const done = statusRaw === 'done';
          const inProgress = !done && (statusRaw === 'in-progress' || statusRaw === 'inprogress' || statusRaw === 'active');

          const priorityRaw = getCol(row, 'priority').toLowerCase() as Priority;
          const priority: Priority = VALID_PRIORITIES.has(priorityRaw) ? priorityRaw : 'medium';

          const estimateRaw = getCol(row, 'estimate') as Estimate;
          const estimate: Estimate = VALID_ESTIMATES.has(estimateRaw) ? estimateRaw : '';

          const valueRaw = getCol(row, 'value') as Estimate;
          const value: Estimate | undefined = VALID_ESTIMATES.has(valueRaw) ? valueRaw : undefined;

          const tagsRaw = getCol(row, 'tags');
          const tags = tagsRaw ? tagsRaw.split(',').map((t) => t.trim().toLowerCase()).filter(Boolean) : [];

          const entityRefsRaw = getCol(row, 'entityrefs');
          const entityRefs = entityRefsRaw
            ? entityRefsRaw.split(',').map((n) => n.trim().toLowerCase()).filter(Boolean)
                .map((name) => entityByName.get(name)).filter((id): id is string => !!id)
            : [];

          const startDate = getCol(row, 'startdate') || undefined;
          const dueDate = getCol(row, 'duedate') || undefined;
          const completedAt = getCol(row, 'completedat') || undefined;
          const url = getCol(row, 'url') || undefined;
          const notes = getCol(row, 'notes') || '';
          const milestone = getMilestoneId(getCol(row, 'milestone'));
          const assignee = getCol(row, 'assignee') || undefined;

          newFeatures.push({
            id: createId(),
            title,
            description: '',
            priority,
            estimate,
            value,
            done,
            inProgress,
            entityRefs,
            milestone,
            tags,
            notes,
            blockedBy: [],
            startDate,
            dueDate,
            completedAt,
            url,
            assignee,
          });
        }

        if (newFeatures.length === 0) {
          resolve({ success: false, message: 'No valid features found in CSV' });
          return;
        }

        useProjectStore.setState((state) => ({
          features: [...state.features, ...newFeatures],
          milestones: [...state.milestones, ...newMilestones],
        }));

        resolve({
          success: true,
          count: newFeatures.length,
          message: `Imported ${newFeatures.length} feature${newFeatures.length !== 1 ? 's' : ''}${
            newMilestones.length > 0
              ? ` · created ${newMilestones.length} milestone${newMilestones.length !== 1 ? 's' : ''}`
              : ''
          }`,
        });
      } catch {
        resolve({ success: false, message: 'Failed to parse CSV file' });
      }
    };
    reader.readAsText(file);
  });
}

// ─── OpenAPI Export ────────────────────────────────────────────────────────────

function colToOpenApiType(col: Column): string {
  switch (col.dataType) {
    case 'uuid': return 'string\n          format: uuid';
    case 'integer': case 'smallint': case 'number': return 'integer';
    case 'bigint': return 'integer\n          format: int64';
    case 'float': case 'decimal': case 'numeric': return 'number';
    case 'boolean': return 'boolean';
    case 'date': return 'string\n          format: date';
    case 'datetime': case 'timestamp': case 'timestamptz': return 'string\n          format: date-time';
    case 'json': case 'jsonb': return 'object';
    case 'array': return 'array\n          items:\n            type: string';
    default: return 'string';
  }
}

function entityToSchema(entity: Entity): string[] {
  const lines: string[] = [];
  const props = entity.columns.map((c) => {
    const typeStr = colToOpenApiType(c);
    const extra = c.nullable ? '' : '';
    const noteStr = c.note ? `\n          description: "${c.note.replace(/"/g, "'")}"` : '';
    return `        ${c.name}:\n          type: ${typeStr}${noteStr}${extra}`;
  });
  const required = entity.columns.filter((c) => !c.nullable && !c.primaryKey).map((c) => `          - ${c.name}`);
  lines.push(`    ${entity.name}:`);
  lines.push('      type: object');
  if (entity.description) lines.push(`      description: "${entity.description.replace(/"/g, "'")}"`);
  if (required.length > 0) {
    lines.push('      required:');
    required.forEach((r) => lines.push(r));
  }
  lines.push('      properties:');
  props.forEach((p) => lines.push(p));
  return lines;
}

export function exportOpenApi(): void {
  const es = useEntityStore.getState();
  const ps = useProjectStore.getState();
  const { meta, endpoints } = ps;
  const { entities } = es;

  const lines: string[] = [];
  const projectName = meta.name || 'Untitled Project';
  const slug = projectName.replace(/\s+/g, '-').toLowerCase();

  lines.push('openapi: "3.0.3"');
  lines.push('info:');
  lines.push(`  title: "${projectName}"`);
  if (meta.description) lines.push(`  description: "${meta.description.replace(/\n/g, ' ').replace(/"/g, "'")}"`);
  lines.push('  version: "0.1.0"');
  lines.push('');

  // Paths
  if (endpoints.length > 0) {
    lines.push('paths:');

    // Group by path
    const byPath = new Map<string, typeof endpoints>();
    endpoints.forEach((ep) => {
      const k = ep.path || '/';
      if (!byPath.has(k)) byPath.set(k, []);
      byPath.get(k)!.push(ep);
    });

    byPath.forEach((eps, path) => {
      // Convert :param to {param}
      const oapiPath = path.replace(/:([a-zA-Z_][a-zA-Z0-9_]*)/g, '{$1}');
      const pathParams = [...path.matchAll(/:([a-zA-Z_][a-zA-Z0-9_]*)/g)].map((m) => m[1]);
      lines.push(`  ${oapiPath}:`);

      eps.forEach((ep) => {
        const method = ep.method.toLowerCase();
        const summary = ep.description || `${ep.method} ${path}`;
        const tags = ep.tag ? [ep.tag] : [];

        lines.push(`    ${method}:`);
        lines.push(`      summary: "${summary}"`);
        if (ep.status === 'deprecated') lines.push('      deprecated: true');
        if (tags.length > 0) {
          lines.push('      tags:');
          tags.forEach((t) => lines.push(`        - ${t}`));
        }
        if (ep.notes?.trim()) lines.push(`      x-notes: "${ep.notes.replace(/"/g, "'").replace(/\n/g, ' ')}"`);
        if (ep.status === 'implemented') lines.push('      x-status: implemented');
        if (ep.rateLimit?.trim()) lines.push(`      x-rate-limit: "${ep.rateLimit.trim()}"`);
        if (ep.version?.trim()) lines.push(`      x-version: "${ep.version.trim()}"`);

        // Path + query parameters
        const queryParamList = (ep.queryParams ?? '').split(',').map((p: string) => p.trim()).filter(Boolean);
        if (pathParams.length > 0 || queryParamList.length > 0) {
          lines.push('      parameters:');
          pathParams.forEach((param) => {
            lines.push(`        - name: ${param}`);
            lines.push('          in: path');
            lines.push('          required: true');
            lines.push('          schema:');
            lines.push('            type: string');
          });
          queryParamList.forEach((param: string) => {
            lines.push(`        - name: ${param}`);
            lines.push('          in: query');
            lines.push('          required: false');
            lines.push('          schema:');
            lines.push('            type: string');
          });
        }

        // Auth / security
        const auth = ep.auth ?? 'none';
        if (auth === 'bearer' || auth === 'oauth2') {
          lines.push('      security:');
          lines.push('        - bearerAuth: []');
        } else if (auth === 'apiKey') {
          lines.push('      security:');
          lines.push('        - apiKeyAuth: []');
        } else if (auth === 'basic') {
          lines.push('      security:');
          lines.push('        - basicAuth: []');
        }

        // Request body for POST/PUT/PATCH
        if (['POST', 'PUT', 'PATCH'].includes(ep.method)) {
          lines.push('      requestBody:');
          lines.push('        required: true');
          lines.push('        content:');
          lines.push('          application/json:');
          lines.push('            schema:');
          if (ep.requestBody?.trim()) {
            lines.push('              description: See requestBody');
          } else if (ep.entityRef) {
            const ent = entities.find((e) => e.id === ep.entityRef);
            lines.push(`              $ref: "#/components/schemas/${ent?.name ?? 'object'}"` );
          } else {
            lines.push('              type: object');
          }
        }

        lines.push('      responses:');
        lines.push('        "200":');
        lines.push('          description: Success');
        if (ep.entityRef && ['GET'].includes(ep.method)) {
          const ent = entities.find((e) => e.id === ep.entityRef);
          if (ent) {
            lines.push('          content:');
            lines.push('            application/json:');
            lines.push('              schema:');
            if (path.includes(':id') || path.includes('{id}')) {
              lines.push(`                $ref: "#/components/schemas/${ent.name}"`);
            } else {
              lines.push('                type: array');
              lines.push('                items:');
              lines.push(`                  $ref: "#/components/schemas/${ent.name}"`);
            }
          }
        }
        if (['DELETE'].includes(ep.method)) {
          lines.push('        "204":');
          lines.push('          description: No content');
        }
      });
    });
    lines.push('');
  }

  // Components
  const usedSchemes = new Set(endpoints.map((ep) => ep.auth ?? 'none').filter((a) => a !== 'none'));
  const hasComponents = entities.length > 0 || usedSchemes.size > 0;
  if (hasComponents) {
    lines.push('components:');

    // Security schemes
    if (usedSchemes.size > 0) {
      lines.push('  securitySchemes:');
      if (usedSchemes.has('bearer') || usedSchemes.has('oauth2')) {
        lines.push('    bearerAuth:');
        lines.push('      type: http');
        lines.push('      scheme: bearer');
        lines.push('      bearerFormat: JWT');
      }
      if (usedSchemes.has('apiKey')) {
        lines.push('    apiKeyAuth:');
        lines.push('      type: apiKey');
        lines.push('      in: header');
        lines.push('      name: X-API-Key');
      }
      if (usedSchemes.has('basic')) {
        lines.push('    basicAuth:');
        lines.push('      type: http');
        lines.push('      scheme: basic');
      }
      lines.push('');
    }

    if (entities.length > 0) {
      lines.push('  schemas:');
      entities.forEach((entity) => {
        entityToSchema(entity).forEach((l) => lines.push(l));
        lines.push('');
      });
    }
  }

  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/yaml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${slug}-openapi.yaml`;
  a.click();
  URL.revokeObjectURL(url);
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function exportHtmlDocs(): void {
  const es = useEntityStore.getState();
  const ps = useProjectStore.getState();
  const { entities } = es;
  const { meta, features, scope, endpoints, milestones } = ps;
  const slug = (meta.name || 'project').replace(/\s+/g, '-').toLowerCase();
  const generatedAt = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });

  const priorityBadge = (p: string) => {
    const colors: Record<string, string> = {
      critical: '#ef4444', high: '#f59e0b', medium: '#6366f1', low: '#64748b', 'nice-to-have': '#6b7280',
    };
    const c = colors[p] ?? '#6366f1';
    return `<span style="background:${c}22;color:${c};border:1px solid ${c}44;font-size:10px;padding:1px 6px;border-radius:4px;font-weight:600;">${esc(p)}</span>`;
  };

  const methodColors: Record<string, string> = {
    GET: '#10b981', POST: '#6366f1', PUT: '#f59e0b', PATCH: '#06b6d4', DELETE: '#ef4444',
  };

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(meta.name || 'Project Docs')}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: #0a0a0b; color: #e2e8f0; line-height: 1.6; }
  .container { max-width: 1100px; margin: 0 auto; padding: 32px 24px; }
  h1 { font-size: 28px; font-weight: 700; color: #f1f5f9; margin-bottom: 6px; }
  h2 { font-size: 18px; font-weight: 600; color: #f1f5f9; margin: 40px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #2a2a30; }
  h3 { font-size: 14px; font-weight: 600; color: #f1f5f9; margin: 0 0 6px; }
  p { color: #94a3b8; font-size: 14px; }
  .meta { color: #64748b; font-size: 13px; margin-bottom: 24px; }
  .tag { display: inline-block; font-size: 11px; padding: 2px 8px; border-radius: 4px; margin-right: 4px; }
  .card { background: #111113; border: 1px solid #2a2a30; border-radius: 10px; overflow: hidden; margin-bottom: 16px; }
  .card-header { padding: 12px 16px; border-bottom: 1px solid #2a2a30; display: flex; align-items: center; gap: 10px; }
  .entity-dot { width: 10px; height: 10px; border-radius: 50%; flex-shrink: 0; }
  .entity-desc { color: #64748b; font-size: 12px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { text-align: left; padding: 8px 12px; color: #64748b; font-size: 11px; text-transform: uppercase; letter-spacing: .06em; border-bottom: 1px solid #2a2a30; font-weight: 600; }
  td { padding: 7px 12px; border-bottom: 1px solid #1a1a1f; color: #94a3b8; vertical-align: middle; }
  tr:last-child td { border-bottom: none; }
  tr:hover td { background: rgba(255,255,255,0.02); }
  .col-name { color: #e2e8f0; font-family: 'JetBrains Mono', 'Fira Code', monospace; font-size: 11px; }
  .badge { font-size: 9px; font-weight: 700; padding: 2px 5px; border-radius: 3px; line-height: 1; display: inline-block; }
  .badge-pk { background: #f59e0b22; color: #f59e0b; }
  .badge-fk { background: #6366f122; color: #6366f1; }
  .badge-uq { background: #10b98122; color: #10b981; }
  .badge-idx { background: #64748b22; color: #94a3b8; }
  .type-pill { font-family: monospace; font-size: 10px; padding: 2px 6px; border-radius: 4px; background: #1a1a1f; border: 1px solid #2a2a30; color: #94a3b8; }
  .method { font-size: 10px; font-weight: 700; padding: 2px 7px; border-radius: 4px; letter-spacing: .04em; }
  .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
  .scope-list { list-style: none; }
  .scope-list li { padding: 4px 0; font-size: 13px; color: #94a3b8; display: flex; align-items: center; gap: 8px; }
  .scope-list li::before { content: ''; width: 6px; height: 6px; border-radius: 50%; flex-shrink: 0; }
  .scope-in li::before { background: #10b981; }
  .scope-out li::before { background: #ef4444; }
  .feat-row { display: flex; align-items: flex-start; gap: 12px; padding: 10px 16px; border-bottom: 1px solid #1a1a1f; }
  .feat-row:last-child { border-bottom: none; }
  .feat-done { text-decoration: line-through; color: #475569; }
  .footer { text-align: center; margin-top: 48px; color: #334155; font-size: 12px; }
  @media (max-width: 680px) { .grid-2 { grid-template-columns: 1fr; } }
</style>
</head>
<body>
<div class="container">
  <h1>${esc(meta.name || 'Untitled Project')}</h1>
  ${meta.description ? `<p style="margin-top:8px;font-size:15px;color:#94a3b8;">${esc(meta.description)}</p>` : ''}
  <p class="meta">Generated by surplan · ${generatedAt}</p>

  ${meta.techStackNotes ? `
  <h2>Tech Stack</h2>
  <div class="card"><div style="padding:14px 16px;color:#94a3b8;font-size:13px;white-space:pre-wrap;">${esc(meta.techStackNotes)}</div></div>
  ` : ''}

  ${scope.length > 0 ? `
  <h2>Scope</h2>
  <div class="grid-2">
    <div>
      <h3 style="color:#10b981;margin-bottom:8px;">In Scope</h3>
      <ul class="scope-list scope-in">${scope.filter((s) => s.inScope).map((s) => `<li>${esc(s.text)}</li>`).join('')}</ul>
    </div>
    <div>
      <h3 style="color:#ef4444;margin-bottom:8px;">Out of Scope</h3>
      <ul class="scope-list scope-out">${scope.filter((s) => !s.inScope).map((s) => `<li>${esc(s.text)}</li>`).join('')}</ul>
    </div>
  </div>
  ` : ''}

  ${entities.length > 0 ? `
  <h2>Database Schema <span style="color:#64748b;font-size:13px;font-weight:400;">(${entities.length} ${entities.length === 1 ? 'entity' : 'entities'})</span></h2>
  ${entities.map((entity) => `
  <div class="card" style="border-left:3px solid ${esc(entity.color)};">
    <div class="card-header">
      <span class="entity-dot" style="background:${esc(entity.color)};"></span>
      <div>
        <h3>${esc(entity.name || 'unnamed')}</h3>
        ${entity.description ? `<span class="entity-desc">${esc(entity.description)}</span>` : ''}
      </div>
      ${entity.tags.length > 0 ? `<div style="margin-left:auto;">${entity.tags.map((t) => `<span class="tag" style="background:${esc(entity.color)}22;color:${esc(entity.color)};border:1px solid ${esc(entity.color)}44;">${esc(t)}</span>`).join('')}</div>` : ''}
    </div>
    <table>
      <thead><tr><th>Column</th><th>Type</th><th>Null</th><th>Constraints</th><th>References</th><th>Note</th></tr></thead>
      <tbody>
        ${entity.columns.map((col) => `
        <tr>
          <td><span class="col-name">${esc(col.name || '—')}</span></td>
          <td><span class="type-pill">${esc(col.dataType)}${col.dataType === 'enum' && col.enumValues ? ` (${esc(col.enumValues.split(',').map((v) => v.trim()).slice(0, 4).join(', '))}${col.enumValues.split(',').length > 4 ? '…' : ''})` : ''}</span></td>
          <td style="color:${col.nullable ? '#94a3b8' : '#475569'}">${col.nullable ? 'yes' : 'no'}</td>
          <td>${[
            col.primaryKey ? '<span class="badge badge-pk">PK</span>' : '',
            col.unique && !col.primaryKey ? '<span class="badge badge-uq">UQ</span>' : '',
            col.indexed && !col.primaryKey ? '<span class="badge badge-idx">IDX</span>' : '',
            col.defaultValue ? `<span class="type-pill" style="font-size:9px;">=${esc(col.defaultValue)}</span>` : '',
            col.check?.trim() ? `<span class="type-pill" style="font-size:9px;" title="CHECK (${esc(col.check.trim())})">CHK</span>` : '',
          ].filter(Boolean).join(' ')}</td>
          <td>${col.references ? `<span style="font-family:monospace;font-size:11px;color:#6366f1;">${esc(col.references.entityName)}.${esc(col.references.columnName)}</span>` : '<span style="color:#334155;">—</span>'}</td>
          <td style="color:#64748b;font-size:11px;">${esc(col.note || '')}</td>
        </tr>`).join('')}
      </tbody>
    </table>
  </div>
  `).join('')}
  ` : ''}

  ${endpoints.length > 0 ? `
  <h2>API Endpoints <span style="color:#64748b;font-size:13px;font-weight:400;">(${endpoints.length})</span></h2>
  <div class="card">
    <table>
      <thead><tr><th>Method</th><th>Path</th><th>Description</th><th>Auth</th><th>Status</th><th>Status Codes</th></tr></thead>
      <tbody>
        ${endpoints.map((ep) => {
          const mc = methodColors[ep.method] ?? '#94a3b8';
          const epStatus = ep.status ?? 'draft';
          const epStatusColor = epStatus === 'implemented' ? '#10b981' : epStatus === 'deprecated' ? '#f59e0b' : '#64748b';
          const epStatusLabel = epStatus === 'implemented' ? '✓ impl' : epStatus === 'deprecated' ? '~ depr' : 'draft';
          return `<tr${epStatus === 'deprecated' ? ' style="opacity:0.6;"' : ''}>
            <td><span class="method" style="background:${mc}22;color:${mc};">${esc(ep.method)}</span></td>
            <td><span style="font-family:monospace;font-size:11px;color:#e2e8f0;">${esc(ep.path || '/')}</span></td>
            <td style="color:#94a3b8;">${esc(ep.description || '')}</td>
            <td style="color:#64748b;font-size:11px;">${ep.auth !== 'none' ? esc(ep.auth) : '—'}</td>
            <td style="font-size:10px;color:${epStatusColor};">${epStatusLabel}</td>
            <td style="color:#64748b;font-size:11px;">${esc(ep.statusCodes || '')}</td>
          </tr>`;
        }).join('')}
      </tbody>
    </table>
  </div>
  ` : ''}

  ${features.length > 0 ? (() => {
    const nowMs = Date.now();
    const dueBadge = (f: Feature) => {
      if (!f.dueDate || f.done) return '';
      const ms = new Date(f.dueDate).getTime();
      const days = Math.ceil((ms - nowMs) / 86400000);
      const overdue = days < 0;
      const soon = days >= 0 && days <= 7;
      const color = overdue ? '#ef4444' : soon ? '#f59e0b' : '#64748b';
      const label = overdue ? `⚠ ${Math.abs(days)}d overdue` : `📅 ${f.dueDate}`;
      return `<span style="font-size:10px;color:${color};background:${color}18;border:1px solid ${color}40;padding:1px 6px;border-radius:4px;">${label}</span>`;
    };
    const overdueCount = features.filter((f) => !f.done && f.dueDate && new Date(f.dueDate).getTime() < nowMs).length;
    return `
  <h2>Features <span style="color:#64748b;font-size:13px;font-weight:400;">(${features.length} · ${features.filter((f) => f.done).length} done · ${features.filter((f) => f.inProgress && !f.done).length} active${overdueCount > 0 ? ` · <span style="color:#ef4444;">${overdueCount} overdue</span>` : ''})</span></h2>
  ${milestones.length > 0 ? milestones.map((ms) => {
    const mFeatures = features.filter((f) => f.milestone === ms.name);
    if (mFeatures.length === 0) return '';
    return `
    <div class="card" style="margin-bottom:16px;">
      <div class="card-header" style="background:${esc(ms.color)}10;border-left:3px solid ${esc(ms.color)};">
        <h3 style="color:${esc(ms.color)};">${esc(ms.name)}</h3>
        ${ms.description ? `<span class="entity-desc">${esc(ms.description)}</span>` : ''}
        ${ms.dueDate ? `<span style="margin-left:auto;font-size:11px;color:#64748b;">Due: ${esc(ms.dueDate)}</span>` : ''}
      </div>
      ${mFeatures.map((f) => `
      <div class="feat-row">
        <span style="font-size:14px;">${f.done ? '✅' : f.inProgress ? '🔆' : '⬜'}</span>
        <div style="flex:1;">
          <p class="${f.done ? 'feat-done' : ''}" style="font-size:13px;color:${f.done ? '#475569' : f.inProgress ? '#f59e0b' : '#e2e8f0'};font-weight:500;">${esc(f.title)}</p>
          ${f.description ? `<p style="font-size:12px;color:#64748b;margin-top:2px;">${esc(f.description)}</p>` : ''}
          ${f.notes ? `<p style="font-size:11px;color:#475569;margin-top:2px;font-style:italic;">${esc(f.notes.slice(0, 120))}${f.notes.length > 120 ? '…' : ''}</p>` : ''}
        </div>
        <div style="display:flex;gap:8px;align-items:center;flex-shrink:0;">${priorityBadge(f.priority)}${f.assignee ? `<span style="font-size:10px;color:#8b5cf6;background:#8b5cf610;border:1px solid #8b5cf630;padding:1px 6px;border-radius:10px;">@${esc(f.assignee)}</span>` : ''}${f.estimate ? `<span style="font-size:10px;color:#64748b;">pts: ${esc(String(f.estimate))}</span>` : ''}${dueBadge(f)}${f.url ? `<a href="${esc(f.url)}" target="_blank" rel="noopener noreferrer" style="font-size:10px;color:#6366f1;text-decoration:none;">🔗 link</a>` : ''}</div>
      </div>`).join('')}
    </div>`;
  }).join('') : `
  <div class="card">
    ${features.map((f) => `
    <div class="feat-row">
      <span style="font-size:14px;">${f.done ? '✅' : f.inProgress ? '🔆' : '⬜'}</span>
      <div style="flex:1;">
        <p class="${f.done ? 'feat-done' : ''}" style="font-size:13px;color:${f.done ? '#475569' : f.inProgress ? '#f59e0b' : '#e2e8f0'};font-weight:500;">${esc(f.title)}</p>
        ${f.description ? `<p style="font-size:12px;color:#64748b;margin-top:2px;">${esc(f.description)}</p>` : ''}
        ${f.notes ? `<p style="font-size:11px;color:#475569;margin-top:2px;font-style:italic;">${esc(f.notes.slice(0, 120))}${f.notes.length > 120 ? '…' : ''}</p>` : ''}
      </div>
      <div style="display:flex;gap:8px;align-items:center;flex-shrink:0;">${priorityBadge(f.priority)}${f.assignee ? `<span style="font-size:10px;color:#8b5cf6;background:#8b5cf610;border:1px solid #8b5cf630;padding:1px 6px;border-radius:10px;">@${esc(f.assignee)}</span>` : ''}${f.estimate ? `<span style="font-size:10px;color:#64748b;">pts: ${esc(String(f.estimate))}</span>` : ''}${dueBadge(f)}${f.url ? `<a href="${esc(f.url)}" target="_blank" rel="noopener noreferrer" style="font-size:10px;color:#6366f1;text-decoration:none;">🔗 link</a>` : ''}</div>
    </div>`).join('')}
  </div>
  `}`;
  })() : ''}

  <div class="footer">Generated by <strong style="color:#6366f1;">surplan</strong></div>
</div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${slug}-docs.html`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Multi-Agent Claude Code Prompt Export ─────────────────────────────────────

export function generateMultiAgentPrompt(): string {
  const es = useEntityStore.getState();
  const ps = useProjectStore.getState();
  const { meta, features, milestones, scope, endpoints } = ps;
  const { entities } = es;

  const name = meta.name || 'Untitled Project';
  const date = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });

  // ── helpers ──────────────────────────────────────────────────────────────────

  const entityBlock = (entity: Entity): string => {
    const rows = entity.columns.map((c) => {
      const flags = [
        c.primaryKey ? '`PK`' : '',
        c.nullable ? '' : '`NOT NULL`',
        c.unique ? '`UNIQUE`' : '',
        c.indexed && !c.primaryKey ? '`INDEX`' : '',
        c.defaultValue ? `default \`${c.defaultValue}\`` : '',
        c.dataType === 'enum' && c.enumValues ? `enum(${c.enumValues})` : '',
        c.references ? `→ \`${c.references.entityName}.${c.references.columnName}\`` : '',
        c.check?.trim() ? `CHECK(${c.check.trim()})` : '',
      ].filter(Boolean).join(' ');
      return `| \`${c.name || '?'}\` | \`${c.dataType}\` | ${flags || '—'} | ${c.note || ''} |`;
    });
    const lines: string[] = [
      `#### ${entity.name}${entity.description ? ` — *${entity.description}*` : ''}`,
      '',
      '| Column | Type | Constraints | Note |',
      '|--------|------|-------------|------|',
      ...rows,
    ];
    return lines.join('\n');
  };

  const endpointBlock = (): string => {
    if (endpoints.length === 0) return '*No endpoints defined.*';
    const tags = Array.from(new Set(endpoints.map((e) => e.tag || 'General')));
    return tags.map((tag) => {
      const eps = endpoints.filter((e) => (e.tag || 'General') === tag);
      const rows = eps.map((ep) => {
        const auth = ep.auth && ep.auth !== 'none' ? ` *(auth: ${ep.auth})*` : '';
        const qp = ep.queryParams?.trim() ? ` *(query: \`${ep.queryParams.trim()}\`)* ` : '';
        const codes = ep.statusCodes?.trim() ? ` → ${ep.statusCodes}` : '';
        const desc = ep.description ? ` — ${ep.description}` : '';
        const impl = ep.status === 'implemented' ? ' ✓' : ep.status === 'deprecated' ? ' ~~deprecated~~' : '';
        let line = `- \`${ep.method}\` \`${ep.path}\`${desc}${auth}${qp}${codes}${impl}`;
        if (ep.requestBody?.trim()) line += `\n  - **Body:** ${ep.requestBody.trim()}`;
        if (ep.responseBody?.trim()) line += `\n  - **Response:** ${ep.responseBody.trim()}`;
        if (ep.notes?.trim()) line += `\n  - **Notes:** ${ep.notes.trim()}`;
        return line;
      });
      return `#### ${tag}\n\n${rows.join('\n')}`;
    }).join('\n\n');
  };

  const featureBlock = (): string => {
    if (features.length === 0) return '*No features defined.*';
    const milestoneMap = new Map(milestones.map((m) => [m.id, m.name]));
    const featureMap = new Map(features.map((f) => [f.id, f.title]));

    const groups: { label: string; items: Feature[] }[] = [
      ...milestones.map((m) => ({
        label: m.name,
        items: features.filter((f) => f.milestone === m.id),
      })),
      { label: 'Backlog', items: features.filter((f) => !f.milestone) },
    ].filter((g) => g.items.length > 0);

    return groups.map(({ label, items }) => {
      const rows = items.map((f) => {
        const status = f.done ? '~~done~~' : f.inProgress ? '**in-progress**' : 'todo';
        const pri = f.priority !== 'medium' ? ` · priority: ${f.priority}` : '';
        const pts = f.estimate ? ` · ${f.estimate}pts` : '';
        const val = f.value ? ` · val:${f.value}` : '';
        const sprint = f.sprint ? ` · sprint: ${f.sprint}` : '';
        const assignee = f.assignee ? ` · @${f.assignee}` : '';
        const due = f.dueDate ? ` · due: ${f.dueDate}` : '';
        const kind = f.kind && f.kind !== 'feature' ? ` · \`${f.kind}\`` : '';
        const blocked = (f.blockedBy ?? []).length > 0
          ? ` · blocked-by: ${f.blockedBy.map((id) => featureMap.get(id) || id).join(', ')}`
          : '';
        const milName = f.milestone ? milestoneMap.get(f.milestone) ?? '' : '';
        void milName; // used via group label
        let row = `- [${f.done ? 'x' : ' '}] **${f.title}** — ${status}${kind}${pri}${pts}${val}${sprint}${assignee}${due}${blocked}`;
        if (f.description) row += `\n  > ${f.description}`;
        if (f.notes?.trim()) row += `\n  > **Acceptance criteria:** ${f.notes.replace(/\n/g, ' ')}`;
        return row;
      });
      const total = items.length;
      const done = items.filter((i) => i.done).length;
      return `#### ${label} *(${done}/${total} done)*\n\n${rows.join('\n')}`;
    }).join('\n\n');
  };

  const scopeBlock = (): string => {
    const inS = scope.filter((s) => s.inScope);
    const outS = scope.filter((s) => !s.inScope);
    const lines: string[] = [];
    if (inS.length > 0) {
      lines.push('**In scope:**');
      inS.forEach((s) => lines.push(`- ${s.text}`));
    }
    if (outS.length > 0) {
      if (lines.length > 0) lines.push('');
      lines.push('**Out of scope:**');
      outS.forEach((s) => lines.push(`- ${s.text}`));
    }
    return lines.length > 0 ? lines.join('\n') : '*No scope defined.*';
  };

  // ── template ─────────────────────────────────────────────────────────────────

  const lines: string[] = [];

  lines.push(`# Claude Code Build Prompt — ${name}`);
  lines.push('');
  lines.push(`> **Copy this entire prompt and paste it into a new Claude Code session.**`);
  lines.push(`> *Generated by surplan · ${date}*`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Your Task');
  lines.push('');
  lines.push(`Build the complete software project described in this document. Read the entire specification before writing any code.`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Protocol (follow in order)');
  lines.push('');
  lines.push('### Phase 1 — Plan (write the plan, no code yet)');
  lines.push('');
  lines.push('Before writing a single line of code:');
  lines.push('');
  lines.push('1. Read the full spec below carefully.');
  lines.push('2. Write a **detailed implementation plan** that covers:');
  lines.push('   - All modules, services, files, and packages you will create.');
  lines.push('   - Which tasks are independent (can run in parallel).');
  lines.push('   - Which tasks are sequential (critical path).');
  lines.push('   - What integration contracts each subagent must expose (types, env vars, API shapes).');
  lines.push('3. Identify **3–6 parallel work streams** — each will become a subagent task.');
  lines.push('   Examples: `db-models`, `api-routes`, `auth`, `frontend-components`, `tests`, `infra`.');
  lines.push('');
  lines.push('### Phase 2 — Questions (strictly filtered)');
  lines.push('');
  lines.push('Only ask a question if it meets **all three criteria**:');
  lines.push('');
  lines.push('1. The answer materially changes the architecture or approach.');
  lines.push('2. The answer cannot be reasonably inferred from the spec or standard best practices.');
  lines.push('3. There is no obvious "recommended default" that a senior developer would just pick.');
  lines.push('');
  lines.push('**Do not ask about:** folder structure, naming conventions, linting config, whether to add tests, boilerplate preferences, or anything with an obvious industry-standard answer.');
  lines.push('');
  lines.push('List questions as a numbered list. If you have none, state that and proceed immediately.');
  lines.push('');
  lines.push('### Phase 3 — Parallel Build with Subagents');
  lines.push('');
  lines.push('Use the **Agent tool** to spawn subagents for independent work streams:');
  lines.push('');
  lines.push('```');
  lines.push('agent: db-agent      → database schema, migrations, ORM models, seed data');
  lines.push('agent: api-agent     → route handlers, controllers, request validation, error handling');
  lines.push('agent: auth-agent    → authentication, authorization, session/token management, guards');
  lines.push('agent: frontend-agent → UI components, pages, state management, API client');
  lines.push('agent: test-agent    → unit tests, integration tests, E2E tests');
  lines.push('```');
  lines.push('');
  lines.push('Each subagent must:');
  lines.push('- Implement its module **completely** (no stubs or TODOs).');
  lines.push('- Write tests covering the happy path and key error cases.');
  lines.push('- Document integration contracts (exported types, required env vars, API surface).');
  lines.push('');
  lines.push('After all subagents complete, the **main thread** should:');
  lines.push('1. Integrate all modules.');
  lines.push('2. Resolve any conflicts or mismatched contracts.');
  lines.push('3. Run the full test suite and fix any failures.');
  lines.push('4. Perform a final smoke test of the complete running system.');
  lines.push('');
  lines.push('### Phase 4 — Commit Cadence');
  lines.push('');
  lines.push('Commit at each meaningful milestone (e.g., after each subagent integration), not after every file. Use descriptive conventional commit messages.');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Project Specification');
  lines.push('');
  lines.push('### Overview');
  lines.push('');
  lines.push(`**Project name:** ${name}`);
  if (meta.description) {
    lines.push(`**Description:** ${meta.description}`);
  }
  if (meta.techStackNotes) {
    lines.push('');
    lines.push('**Tech stack:**');
    lines.push('');
    meta.techStackNotes.trim().split('\n').forEach((l) => lines.push(l));
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('### Scope');
  lines.push('');
  lines.push(scopeBlock());
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('### Data Model');
  lines.push('');
  if (entities.length === 0) {
    lines.push('*No entities defined.*');
  } else {
    entities.forEach((e) => {
      lines.push(entityBlock(e));
      lines.push('');
    });
  }
  lines.push('---');
  lines.push('');
  lines.push('### API Endpoints');
  lines.push('');
  lines.push(endpointBlock());
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('### Features & Requirements');
  lines.push('');
  lines.push(featureBlock());
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by [surplan](https://surplan.xyz) — local-first project planning for developers.*`);

  return lines.join('\n');
}

// ─── GitHub Issues Markdown Export ─────────────────────────────────────────────

const PRIORITY_LABEL: Record<Priority, string> = {
  critical: '🔴 Critical',
  high: '🟠 High',
  medium: '🟡 Medium',
  low: '🔵 Low',
  'nice-to-have': '⚪ Nice-to-have',
};

export function exportGithubIssues(): void {
  const ps = useProjectStore.getState();
  const { features, milestones, meta } = ps;

  const milestoneMap = new Map(milestones.map((m) => [m.id, m]));
  const featureMap = new Map(features.map((f) => [f.id, f]));
  const slug = (meta.name || 'surplan-project').replace(/\s+/g, '-').toLowerCase();

  const lines: string[] = [];
  lines.push(`# ${meta.name || 'Project'} — GitHub Issues`);
  lines.push('');
  lines.push(`> Exported ${new Date().toLocaleDateString()} from surplan`);
  lines.push('');

  // Group by milestone
  const byMilestone = new Map<string, Feature[]>();
  features.forEach((f) => {
    const key = f.milestone || '__none__';
    if (!byMilestone.has(key)) byMilestone.set(key, []);
    byMilestone.get(key)!.push(f);
  });

  const orderedMilestones: string[] = [...milestones.map((m) => m.id), '__none__'];

  orderedMilestones.forEach((msId) => {
    const group = byMilestone.get(msId);
    if (!group || group.length === 0) return;
    const ms = milestoneMap.get(msId);
    if (ms) {
      lines.push(`## Milestone: ${ms.name}${ms.dueDate ? ` (due ${new Date(ms.dueDate).toLocaleDateString()})` : ''}`);
      if (ms.description) lines.push(`> ${ms.description}`);
    } else {
      lines.push('## No Milestone');
    }
    lines.push('');

    group.forEach((f) => {
      const status = f.done ? '✅ Done' : f.inProgress ? '🔆 In Progress' : '⬜ Todo';
      lines.push(`### ${f.title}`);
      lines.push('');
      lines.push('| Field | Value |');
      lines.push('|-------|-------|');
      lines.push(`| Status | ${status} |`);
      lines.push(`| Priority | ${PRIORITY_LABEL[f.priority]} |`);
      if (f.estimate) lines.push(`| Estimate | ${f.estimate === '?' ? '?' : `${f.estimate} pts`} |`);
      if (f.value) lines.push(`| Value | ${f.value === '?' ? '?' : `${f.value} pts`} |`);
      if (f.dueDate) lines.push(`| Due | ${new Date(f.dueDate).toLocaleDateString()} |`);
      if (f.startDate) lines.push(`| Start | ${new Date(f.startDate).toLocaleDateString()} |`);
      if (f.assignee) lines.push(`| Assignee | @${f.assignee} |`);
      if ((f.tags ?? []).length > 0) lines.push(`| Tags | ${f.tags.map((t) => `\`${t}\``).join(', ')} |`);
      if (f.url) lines.push(`| Link | [${f.url}](${f.url}) |`);
      lines.push('');
      if (f.description) {
        lines.push(f.description);
        lines.push('');
      }
      const blockers = (f.blockedBy ?? []).map((bid) => featureMap.get(bid)?.title).filter(Boolean);
      if (blockers.length > 0) {
        lines.push(`**Blocked by:** ${blockers.map((t) => `_${t}_`).join(', ')}`);
        lines.push('');
      }
      if (f.notes?.trim()) {
        lines.push('**Acceptance Criteria / Notes:**');
        lines.push('');
        f.notes.trim().split('\n').forEach((l) => lines.push(l));
        lines.push('');
      }
      lines.push('---');
      lines.push('');
    });
  });

  const md = lines.join('\n');
  const mdBlob = new Blob([md], { type: 'text/markdown' });
  const mdUrl = URL.createObjectURL(mdBlob);
  const a2 = document.createElement('a');
  a2.href = mdUrl;
  a2.download = `${slug}-github-issues.md`;
  a2.click();
  URL.revokeObjectURL(mdUrl);
}

// ---------------------------------------------------------------------------
// Changelog export — grouped by milestone, done features only
// ---------------------------------------------------------------------------
export function exportChangelog(): void {
  const ps = useProjectStore.getState();
  const { features, milestones, meta } = ps;
  const projectName = meta.name || 'Untitled Project';
  const slug = projectName.replace(/\s+/g, '-').toLowerCase();

  const done = features.filter((f) => f.done);
  if (done.length === 0) return;

  const lines: string[] = [];
  lines.push(`# Changelog — ${projectName}`);
  lines.push('');
  lines.push(`_Generated ${new Date().toLocaleDateString()}_`);
  lines.push('');

  // Group by milestone, then "Backlog" bucket for features without milestone
  const byMilestone = new Map<string, Feature[]>();
  const noMilestone: Feature[] = [];

  done.forEach((f) => {
    if (f.milestone) {
      if (!byMilestone.has(f.milestone)) byMilestone.set(f.milestone, []);
      byMilestone.get(f.milestone)!.push(f);
    } else {
      noMilestone.push(f);
    }
  });

  // Sort milestones by their order in the milestones array
  const orderedMilestones = milestones
    .filter((m) => byMilestone.has(m.id) || byMilestone.has(m.name))
    .map((m) => {
      const features = byMilestone.get(m.id) ?? byMilestone.get(m.name) ?? [];
      return { label: m.name, features, dueDate: m.dueDate };
    });

  // Also catch any milestone string that didn't resolve to a milestone object
  byMilestone.forEach((feats, key) => {
    const found = milestones.some((m) => m.id === key || m.name === key);
    if (!found) {
      orderedMilestones.push({ label: key, features: feats, dueDate: undefined });
    }
  });

  const writeGroup = (label: string, feats: Feature[], dueDate?: string) => {
    lines.push(`## ${label}${dueDate ? ` _(${dueDate})_` : ''}`);
    lines.push('');
    // Group by kind within milestone
    const byKind = new Map<string, Feature[]>();
    feats.forEach((f) => {
      const k = f.kind ?? 'feature';
      if (!byKind.has(k)) byKind.set(k, []);
      byKind.get(k)!.push(f);
    });
    const kindOrder = ['feature', 'improvement', 'bug', 'chore'];
    const kindEmoji: Record<string, string> = { feature: '✨', improvement: '⚡', bug: '🐛', chore: '🔧' };
    kindOrder.forEach((k) => {
      const kFeats = byKind.get(k);
      if (!kFeats?.length) return;
      lines.push(`### ${kindEmoji[k] ?? '·'} ${k.charAt(0).toUpperCase() + k.slice(1)}s`);
      lines.push('');
      kFeats.forEach((f) => {
        const tags = f.tags?.length ? ` \`${f.tags.join('` `')}\`` : '';
        const assignee = f.assignee ? ` _(${f.assignee})_` : '';
        const pts = f.estimate && f.estimate !== '?' ? ` [${f.estimate}pt]` : '';
        const completedAt = f.completedAt
          ? ` — _done ${new Date(f.completedAt).toLocaleDateString()}_`
          : '';
        lines.push(`- **${f.title}**${pts}${assignee}${tags}${completedAt}`);
        if (f.description?.trim()) {
          lines.push(`  ${f.description.trim()}`);
        }
        if (f.checklist?.length) {
          const doneCount = f.checklist.filter((c) => c.done).length;
          lines.push(`  ✅ ${doneCount}/${f.checklist.length} subtasks`);
        }
      });
      lines.push('');
    });
    // Any kinds not in kindOrder
    byKind.forEach((kFeats, k) => {
      if (kindOrder.includes(k)) return;
      lines.push(`### · ${k}`);
      lines.push('');
      kFeats.forEach((f) => {
        lines.push(`- **${f.title}**`);
      });
      lines.push('');
    });
  };

  orderedMilestones.forEach(({ label, features: feats, dueDate }) => {
    writeGroup(label, feats, dueDate);
  });

  if (noMilestone.length > 0) {
    writeGroup('Unplanned', noMilestone);
  }

  // Footer stats
  lines.push('---');
  lines.push('');
  const totalPts = done.reduce((s, f) => {
    const n = parseInt(f.estimate ?? '', 10);
    return s + (isNaN(n) ? 0 : n);
  }, 0);
  lines.push(`**Total:** ${done.length} features shipped · ${totalPts} story points`);

  const md = lines.join('\n');
  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${slug}-changelog.md`;
  a.click();
  URL.revokeObjectURL(url);
}
