import type { Priority, DataType, ForeignKeyRef } from '../types';

export interface ColumnSuggestion {
  name: string;
  dataType: DataType;
  nullable?: boolean;
  primaryKey?: boolean;
  unique?: boolean;
  defaultValue?: string;
  note?: string;
  references?: ForeignKeyRef | null;
  fkLabel?: string; // shown when this is an auto-detected FK suggestion
}

export const COLUMN_SUGGESTIONS: ColumnSuggestion[] = [
  { name: 'id', dataType: 'uuid', nullable: false, primaryKey: true, note: '' },
  { name: 'created_at', dataType: 'timestamp', nullable: false, defaultValue: 'now()' },
  { name: 'updated_at', dataType: 'timestamp', nullable: false, defaultValue: 'now()' },
  { name: 'deleted_at', dataType: 'timestamp', nullable: true },
  { name: 'email', dataType: 'varchar', nullable: false, unique: true },
  { name: 'name', dataType: 'varchar', nullable: false },
  { name: 'first_name', dataType: 'varchar', nullable: true },
  { name: 'last_name', dataType: 'varchar', nullable: true },
  { name: 'username', dataType: 'varchar', nullable: false, unique: true },
  { name: 'password_hash', dataType: 'text', nullable: false },
  { name: 'title', dataType: 'varchar', nullable: false },
  { name: 'description', dataType: 'text', nullable: true },
  { name: 'slug', dataType: 'varchar', nullable: false, unique: true },
  { name: 'body', dataType: 'text', nullable: true },
  { name: 'content', dataType: 'text', nullable: true },
  { name: 'status', dataType: 'varchar', nullable: false },
  { name: 'type', dataType: 'varchar', nullable: false },
  { name: 'role', dataType: 'varchar', nullable: false },
  { name: 'is_active', dataType: 'boolean', nullable: false, defaultValue: 'true' },
  { name: 'is_deleted', dataType: 'boolean', nullable: false, defaultValue: 'false' },
  { name: 'is_verified', dataType: 'boolean', nullable: false, defaultValue: 'false' },
  { name: 'is_published', dataType: 'boolean', nullable: false, defaultValue: 'false' },
  { name: 'published_at', dataType: 'timestamp', nullable: true },
  { name: 'expires_at', dataType: 'timestamp', nullable: true },
  { name: 'token', dataType: 'text', nullable: false, unique: true },
  { name: 'refresh_token', dataType: 'text', nullable: true },
  { name: 'avatar_url', dataType: 'text', nullable: true },
  { name: 'image_url', dataType: 'text', nullable: true },
  { name: 'url', dataType: 'text', nullable: true },
  { name: 'phone', dataType: 'varchar', nullable: true },
  { name: 'address', dataType: 'text', nullable: true },
  { name: 'city', dataType: 'varchar', nullable: true },
  { name: 'country', dataType: 'varchar', nullable: true },
  { name: 'zip_code', dataType: 'varchar', nullable: true },
  { name: 'latitude', dataType: 'float', nullable: true },
  { name: 'longitude', dataType: 'float', nullable: true },
  { name: 'price', dataType: 'decimal', nullable: false },
  { name: 'amount', dataType: 'decimal', nullable: false },
  { name: 'quantity', dataType: 'integer', nullable: false, defaultValue: '0' },
  { name: 'count', dataType: 'integer', nullable: false, defaultValue: '0' },
  { name: 'order', dataType: 'integer', nullable: false, defaultValue: '0' },
  { name: 'sort_order', dataType: 'integer', nullable: false, defaultValue: '0' },
  { name: 'position', dataType: 'integer', nullable: false, defaultValue: '0' },
  { name: 'metadata', dataType: 'json', nullable: true },
  { name: 'settings', dataType: 'json', nullable: true },
  { name: 'tags', dataType: 'json', nullable: true },
  { name: 'notes', dataType: 'text', nullable: true },
  { name: 'color', dataType: 'varchar', nullable: true },
  { name: 'icon', dataType: 'varchar', nullable: true },
  { name: 'locale', dataType: 'varchar', nullable: true, defaultValue: "'en'" },
  { name: 'timezone', dataType: 'varchar', nullable: true },
  { name: 'version', dataType: 'integer', nullable: false, defaultValue: '1' },
  { name: 'checksum', dataType: 'varchar', nullable: true },
  // Auth / security
  { name: 'password_salt', dataType: 'text', nullable: true },
  { name: 'api_key', dataType: 'text', nullable: true, unique: true },
  { name: 'secret_key', dataType: 'text', nullable: true },
  { name: 'public_key', dataType: 'text', nullable: true },
  { name: 'access_token', dataType: 'text', nullable: true },
  { name: 'reset_token', dataType: 'text', nullable: true, unique: true },
  { name: 'verification_token', dataType: 'text', nullable: true, unique: true },
  { name: 'session_token', dataType: 'text', nullable: true, unique: true },
  { name: 'two_factor_secret', dataType: 'text', nullable: true },
  // Timestamps (lifecycle)
  { name: 'last_login_at', dataType: 'timestamp', nullable: true },
  { name: 'verified_at', dataType: 'timestamp', nullable: true },
  { name: 'confirmed_at', dataType: 'timestamp', nullable: true },
  { name: 'activated_at', dataType: 'timestamp', nullable: true },
  { name: 'deactivated_at', dataType: 'timestamp', nullable: true },
  { name: 'archived_at', dataType: 'timestamp', nullable: true },
  { name: 'completed_at', dataType: 'timestamp', nullable: true },
  { name: 'started_at', dataType: 'timestamp', nullable: true },
  { name: 'ended_at', dataType: 'timestamp', nullable: true },
  { name: 'due_at', dataType: 'timestamp', nullable: true },
  { name: 'scheduled_at', dataType: 'timestamp', nullable: true },
  { name: 'sent_at', dataType: 'timestamp', nullable: true },
  { name: 'read_at', dataType: 'timestamp', nullable: true },
  { name: 'approved_at', dataType: 'timestamp', nullable: true },
  { name: 'rejected_at', dataType: 'timestamp', nullable: true },
  { name: 'cancelled_at', dataType: 'timestamp', nullable: true },
  { name: 'failed_at', dataType: 'timestamp', nullable: true },
  // File / media
  { name: 'file_path', dataType: 'text', nullable: true },
  { name: 'file_name', dataType: 'varchar', nullable: true },
  { name: 'file_size', dataType: 'bigint', nullable: true },
  { name: 'mime_type', dataType: 'varchar', nullable: true },
  { name: 'extension', dataType: 'varchar', nullable: true },
  { name: 'width', dataType: 'integer', nullable: true },
  { name: 'height', dataType: 'integer', nullable: true },
  { name: 'duration', dataType: 'integer', nullable: true },
  { name: 'thumbnail_url', dataType: 'text', nullable: true },
  { name: 'cover_url', dataType: 'text', nullable: true },
  { name: 'file_url', dataType: 'text', nullable: true },
  { name: 'bucket', dataType: 'varchar', nullable: true },
  { name: 'storage_key', dataType: 'text', nullable: true },
  // Commerce / billing
  { name: 'price', dataType: 'decimal', nullable: false },
  { name: 'subtotal', dataType: 'decimal', nullable: false, defaultValue: '0' },
  { name: 'total', dataType: 'decimal', nullable: false, defaultValue: '0' },
  { name: 'tax', dataType: 'decimal', nullable: true, defaultValue: '0' },
  { name: 'discount', dataType: 'decimal', nullable: true, defaultValue: '0' },
  { name: 'currency', dataType: 'varchar', nullable: false, defaultValue: "'USD'" },
  { name: 'stripe_customer_id', dataType: 'varchar', nullable: true, unique: true },
  { name: 'stripe_subscription_id', dataType: 'varchar', nullable: true },
  { name: 'plan', dataType: 'varchar', nullable: true },
  // Request / analytics context
  { name: 'ip_address', dataType: 'varchar', nullable: true },
  { name: 'user_agent', dataType: 'text', nullable: true },
  { name: 'referer', dataType: 'text', nullable: true },
  { name: 'source', dataType: 'varchar', nullable: true },
  { name: 'medium', dataType: 'varchar', nullable: true },
  { name: 'campaign', dataType: 'varchar', nullable: true },
  // Profile / social
  { name: 'bio', dataType: 'text', nullable: true },
  { name: 'website', dataType: 'text', nullable: true },
  { name: 'display_name', dataType: 'varchar', nullable: true },
  { name: 'full_name', dataType: 'varchar', nullable: true },
  { name: 'gender', dataType: 'varchar', nullable: true },
  { name: 'birthdate', dataType: 'date', nullable: true },
  // Numeric / dimensions
  { name: 'weight', dataType: 'decimal', nullable: true },
  { name: 'rating', dataType: 'decimal', nullable: true },
  { name: 'score', dataType: 'integer', nullable: true, defaultValue: '0' },
  { name: 'rank', dataType: 'integer', nullable: true },
  { name: 'priority', dataType: 'integer', nullable: false, defaultValue: '0' },
  { name: 'retry_count', dataType: 'integer', nullable: false, defaultValue: '0' },
  { name: 'max_retries', dataType: 'integer', nullable: false, defaultValue: '3' },
  // Error / job tracking
  { name: 'error_message', dataType: 'text', nullable: true },
  { name: 'error_code', dataType: 'varchar', nullable: true },
  { name: 'job_id', dataType: 'varchar', nullable: true },
  { name: 'task_id', dataType: 'varchar', nullable: true },
  { name: 'trace_id', dataType: 'varchar', nullable: true },
  // Misc
  { name: 'language', dataType: 'varchar', nullable: true, defaultValue: "'en'" },
  { name: 'excerpt', dataType: 'text', nullable: true },
  { name: 'summary', dataType: 'text', nullable: true },
  { name: 'config', dataType: 'json', nullable: true },
  { name: 'extra', dataType: 'json', nullable: true },
  { name: 'payload', dataType: 'json', nullable: true },
  { name: 'headers', dataType: 'json', nullable: true },
];

export const PRIORITY_CONFIG: Record<Priority, { label: string; classes: string }> = {
  critical: { label: 'Critical', classes: 'bg-red-500/20 text-red-400 border border-red-500/30' },
  high: { label: 'High', classes: 'bg-orange-500/20 text-orange-400 border border-orange-500/30' },
  medium: { label: 'Medium', classes: 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/30' },
  low: { label: 'Low', classes: 'bg-blue-500/20 text-blue-400 border border-blue-500/30' },
  'nice-to-have': { label: 'Nice to Have', classes: 'bg-zinc-500/20 text-zinc-400 border border-zinc-500/30' },
};

export const PRIORITIES: Priority[] = ['critical', 'high', 'medium', 'low', 'nice-to-have'];
