import type { Entity, Column, ExportFormat, FrontendExportFormat, Page, UIComponent, DesignTokens } from '../types';

// ─── SQL Type Mapping ─────────────────────────────────────────────────────────

function toPostgresType(col: Column): string {
  switch (col.dataType) {
    case 'uuid': return 'UUID';
    case 'string': case 'varchar': return 'VARCHAR(255)';
    case 'char': return 'CHAR(1)';
    case 'text': return 'TEXT';
    case 'integer': case 'number': return 'INTEGER';
    case 'smallint': return 'SMALLINT';
    case 'bigint': return 'BIGINT';
    case 'float': return 'FLOAT';
    case 'decimal': case 'numeric': return 'DECIMAL(10, 2)';
    case 'boolean': return 'BOOLEAN';
    case 'date': return 'DATE';
    case 'datetime': case 'timestamp': return 'TIMESTAMP';
    case 'timestamptz': return 'TIMESTAMPTZ';
    case 'time': return 'TIME';
    case 'json': return 'JSON';
    case 'jsonb': return 'JSONB';
    case 'enum': {
      const vals = col.enumValues?.split(',').map((v) => `'${v.trim()}'`).filter(Boolean).join(', ');
      return vals ? `VARCHAR(50) CHECK (${col.name || 'col'} IN (${vals}))` : `VARCHAR(50) /* enum */`;
    }
    case 'blob': case 'bytea': return 'BYTEA';
    case 'array': return 'TEXT[]';
    default: return 'TEXT';
  }
}

function toMysqlType(col: Column): string {
  switch (col.dataType) {
    case 'uuid': return 'CHAR(36)';
    case 'string': case 'varchar': return 'VARCHAR(255)';
    case 'char': return 'CHAR(1)';
    case 'text': return 'TEXT';
    case 'integer': case 'number': return 'INT';
    case 'smallint': return 'SMALLINT';
    case 'bigint': return 'BIGINT';
    case 'float': return 'FLOAT';
    case 'decimal': case 'numeric': return 'DECIMAL(10, 2)';
    case 'boolean': return 'TINYINT(1)';
    case 'date': return 'DATE';
    case 'datetime': case 'timestamp': case 'timestamptz': return 'DATETIME';
    case 'time': return 'TIME';
    case 'json': case 'jsonb': return 'JSON';
    case 'enum': {
      const vals = col.enumValues?.split(',').map((v) => `'${v.trim()}'`).filter(Boolean).join(', ');
      return vals ? `ENUM(${vals})` : `ENUM(/* values */)`;
    }
    case 'blob': case 'bytea': return 'BLOB';
    default: return 'TEXT';
  }
}

function toSqliteType(col: Column): string {
  switch (col.dataType) {
    case 'integer': case 'smallint': case 'bigint': case 'number': return 'INTEGER';
    case 'float': case 'decimal': case 'numeric': return 'REAL';
    case 'boolean': return 'INTEGER';
    case 'json': case 'jsonb': case 'array': return 'TEXT';
    case 'blob': case 'bytea': return 'BLOB';
    default: return 'TEXT';
  }
}

// ─── SQL DDL Export ───────────────────────────────────────────────────────────

function exportSql(entities: Entity[], dialect: 'postgres' | 'mysql' | 'sqlite'): string {
  const lines: string[] = [];
  const q = dialect === 'mysql' ? '`' : '"';

  lines.push(`-- Generated by surplan`);
  lines.push(`-- Dialect: ${dialect}`);
  lines.push(`-- ${new Date().toISOString()}`);
  lines.push('');

  for (const entity of entities) {
    const tableName = entity.name || 'unnamed_table';
    if (entity.description) {
      lines.push(`-- ${entity.description}`);
    }
    lines.push(`CREATE TABLE ${q}${tableName}${q} (`);

    const cols = [...entity.columns].sort((a, b) => a.order - b.order);
    const colDefs: string[] = [];
    const constraints: string[] = [];

    for (const col of cols) {
      if (!col.name) continue;
      let typeFn = toPostgresType;
      if (dialect === 'mysql') typeFn = toMysqlType;
      if (dialect === 'sqlite') typeFn = toSqliteType;

      let def = `  ${q}${col.name}${q} ${typeFn(col)}`;
      if (!col.nullable) def += ' NOT NULL';
      if (col.unique) def += ' UNIQUE';
      if (col.defaultValue) {
        // Don't quote SQL function calls, keywords, or numeric values
        const isSqlExpr = /^\s*(\w+\s*\(|\d|true$|false$|null$|current_\w+$)/i.test(col.defaultValue.trim());
        const isStringType = !isSqlExpr && ['string', 'text', 'varchar', 'char', 'uuid', 'enum'].includes(col.dataType);
        def += ` DEFAULT ${isStringType ? `'${col.defaultValue}'` : col.defaultValue}`;
      }
      if (col.note) def += ` -- ${col.note}`;
      colDefs.push(def);
    }

    // Primary key constraint
    const pks = cols.filter((c) => c.primaryKey && c.name);
    if (pks.length > 0) {
      constraints.push(`  PRIMARY KEY (${pks.map((c) => `${q}${c.name}${q}`).join(', ')})`);
    }

    // FK constraints (postgres/mysql only)
    if (dialect !== 'sqlite') {
      for (const col of cols) {
        if (col.references && col.name && col.references.entityName && col.references.columnName) {
          constraints.push(
            `  CONSTRAINT fk_${tableName}_${col.name} FOREIGN KEY (${q}${col.name}${q}) REFERENCES ${q}${col.references.entityName}${q} (${q}${col.references.columnName}${q})`
          );
        }
      }
    }

    // CHECK constraints
    for (const col of cols) {
      if (col.check?.trim() && col.name) {
        constraints.push(`  CONSTRAINT chk_${tableName}_${col.name} CHECK (${col.check.trim()})`);
      }
    }

    lines.push([...colDefs, ...constraints].join(',\n'));
    lines.push(');');

    // Indexes
    for (const col of cols) {
      if (col.indexed && !col.primaryKey && col.name) {
        lines.push(`CREATE INDEX idx_${tableName}_${col.name} ON ${q}${tableName}${q} (${q}${col.name}${q});`);
      }
    }

    // COMMENT ON statements (PostgreSQL only)
    if (dialect === 'postgres') {
      if (entity.description) {
        lines.push(`COMMENT ON TABLE ${q}${tableName}${q} IS '${entity.description.replace(/'/g, "''")}';`);
      }
      for (const col of cols) {
        if (col.note && col.name) {
          lines.push(`COMMENT ON COLUMN ${q}${tableName}${q}.${q}${col.name}${q} IS '${col.note.replace(/'/g, "''")}';`);
        }
      }
    }

    lines.push('');
  }

  return lines.join('\n');
}

// ─── TypeScript Export ────────────────────────────────────────────────────────

function tsType(col: Column): string {
  switch (col.dataType) {
    case 'enum': {
      const vals = col.enumValues?.split(',').map((v) => `'${v.trim()}'`).filter(Boolean);
      return vals && vals.length > 0 ? vals.join(' | ') : 'string';
    }
    case 'uuid': case 'string': case 'varchar': case 'text': case 'char': return 'string';
    case 'integer': case 'smallint': case 'bigint': case 'float': case 'decimal': case 'numeric': case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'date': case 'datetime': case 'timestamp': case 'timestamptz': return 'Date';
    case 'time': return 'string';
    case 'json': case 'jsonb': return 'Record<string, unknown>';
    case 'array': return 'unknown[]';
    case 'blob': case 'bytea': return 'Buffer';
    default: return 'unknown';
  }
}

function toPascalCase(s: string): string {
  return s
    .split(/[_\s-]+/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

function exportTypeScript(entities: Entity[]): string {
  const lines: string[] = [];
  lines.push('// Generated by surplan');
  lines.push(`// ${new Date().toISOString()}`);
  lines.push('');

  for (const entity of entities) {
    const interfaceName = toPascalCase(entity.name || 'Unknown');
    if (entity.description) {
      lines.push(`/** ${entity.description} */`);
    }
    lines.push(`export interface ${interfaceName} {`);
    const cols = [...entity.columns].sort((a, b) => a.order - b.order);
    for (const col of cols) {
      if (!col.name) continue;
      const opt = col.nullable ? '?' : '';
      const type = tsType(col) + (col.nullable ? ' | null' : '');
      if (col.note) lines.push(`  /** ${col.note} */`);
      lines.push(`  ${col.name}${opt}: ${type};`);
    }
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

// ─── Prisma Export ────────────────────────────────────────────────────────────

function prismaType(col: Column): string {
  switch (col.dataType) {
    case 'enum': return toPascalCase(col.name || 'Enum'); // Prisma uses named enum types
    case 'uuid': case 'string': case 'varchar': case 'text': case 'char': return 'String';
    case 'integer': case 'smallint': case 'number': return 'Int';
    case 'bigint': return 'BigInt';
    case 'float': return 'Float';
    case 'decimal': case 'numeric': return 'Decimal';
    case 'boolean': return 'Boolean';
    case 'date': return 'DateTime';
    case 'datetime': case 'timestamp': case 'timestamptz': return 'DateTime';
    case 'time': return 'String';
    case 'json': case 'jsonb': return 'Json';
    case 'array': return 'String[]';
    case 'blob': case 'bytea': return 'Bytes';
    default: return 'String';
  }
}

function toCamelCase(s: string): string {
  return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

function prismaDbAnnotation(col: Column): string | null {
  switch (col.dataType) {
    case 'uuid': return '@db.Uuid';
    case 'text': return '@db.Text';
    case 'varchar': case 'string': return '@db.VarChar(255)';
    case 'char': return '@db.Char(1)';
    case 'smallint': return '@db.SmallInt';
    case 'bigint': return '@db.BigInt';
    case 'decimal': case 'numeric': return '@db.Decimal(10, 2)';
    case 'timestamptz': return '@db.Timestamptz(3)';
    case 'jsonb': return '@db.JsonB';
    case 'bytea': case 'blob': return '@db.ByteA';
    default: return null;
  }
}

function exportPrisma(entities: Entity[]): string {
  const lines: string[] = [];
  lines.push('// Generated by surplan');
  lines.push(`// ${new Date().toISOString()}`);
  lines.push('');
  lines.push('generator client {');
  lines.push('  provider = "prisma-client-js"');
  lines.push('}');
  lines.push('');
  lines.push('datasource db {');
  lines.push('  provider = "postgresql"');
  lines.push('  url      = env("DATABASE_URL")');
  lines.push('}');
  lines.push('');

  // Emit Prisma enum declarations for enum columns
  const enumCols = entities.flatMap((e) =>
    e.columns.filter((c) => c.dataType === 'enum' && c.name && c.enumValues?.trim())
  );
  if (enumCols.length > 0) {
    const seen = new Set<string>();
    for (const col of enumCols) {
      const enumName = toPascalCase(col.name);
      if (seen.has(enumName)) continue;
      seen.add(enumName);
      const vals = col.enumValues.split(',').map((v) => v.trim()).filter(Boolean);
      if (vals.length === 0) continue;
      lines.push(`enum ${enumName} {`);
      vals.forEach((v) => lines.push(`  ${v.toUpperCase().replace(/\s+/g, '_')}`));
      lines.push('}');
      lines.push('');
    }
  }

  for (const entity of entities) {
    const modelName = toPascalCase(entity.name || 'Unknown');
    const tableName = entity.name || 'unknown_table';
    if (entity.description) {
      lines.push(`/// ${entity.description}`);
    }
    lines.push(`model ${modelName} {`);

    const cols = [...entity.columns].sort((a, b) => a.order - b.order);
    const blockAttrs: string[] = []; // @@index, @@unique multi, @@map

    // Collect relation targets for reverse relation fields
    const relationFields: { name: string; type: string; attr: string }[] = [];

    for (const col of cols) {
      if (!col.name) continue;
      const fieldName = toCamelCase(col.name);
      const isCamelMapped = fieldName !== col.name;
      let type = prismaType(col);
      if (col.nullable) type += '?';

      const attrs: string[] = [];
      if (col.primaryKey) attrs.push('@id');
      if (col.dataType === 'uuid' && col.primaryKey) attrs.push('@default(uuid())');
      if (col.unique) attrs.push('@unique');
      if (col.defaultValue && !col.primaryKey) {
        const needsQuotes = ['string', 'varchar', 'text', 'char'].includes(col.dataType);
        const val = col.defaultValue;
        if (needsQuotes && !val.startsWith('"') && !val.startsWith("'") && val !== 'now()' && !val.startsWith('auto'))
          attrs.push(`@default("${val}")`);
        else
          attrs.push(`@default(${val})`);
      }
      const dbAnnotation = prismaDbAnnotation(col);
      if (dbAnnotation) attrs.push(dbAnnotation);
      if (isCamelMapped) attrs.push(`@map("${col.name}")`);

      if (col.references?.entityName) {
        const relName = toCamelCase(col.references.entityName);
        const relModel = toPascalCase(col.references.entityName);
        const refField = toCamelCase(col.references.columnName);
        attrs.push(`@relation("${relModel}To${modelName}", fields: [${fieldName}], references: [${refField}])`);
        // Add reverse relation field
        const reverseType = col.nullable ? `${relModel}?` : relModel;
        relationFields.push({
          name: relName,
          type: reverseType,
          attr: `@relation("${relModel}To${modelName}")`,
        });
      }

      if (col.note) lines.push(`  /// ${col.note}`);
      lines.push(`  ${fieldName.padEnd(20)} ${type.padEnd(12)} ${attrs.join(' ')}`.trimEnd());

      // Block-level index
      if (col.indexed && !col.primaryKey) {
        blockAttrs.push(`@@index([${fieldName}])`);
      }
    }

    // Reverse relation fields
    if (relationFields.length > 0) {
      lines.push('');
      for (const rf of relationFields) {
        lines.push(`  ${rf.name.padEnd(20)} ${rf.type.padEnd(12)} ${rf.attr}`);
      }
    }

    // @@map for snake_case table names
    if (tableName.includes('_') || tableName !== tableName.toLowerCase()) {
      blockAttrs.push(`@@map("${tableName}")`);
    }

    if (blockAttrs.length > 0) {
      lines.push('');
      blockAttrs.forEach((a) => lines.push(`  ${a}`));
    }

    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

// ─── Mermaid ER Diagram ───────────────────────────────────────────────────────

function exportMermaid(entities: Entity[]): string {
  const lines: string[] = [];
  lines.push('erDiagram');
  lines.push('');

  for (const entity of entities) {
    if (!entity.name) continue;
    lines.push(`  ${entity.name} {`);
    const cols = [...entity.columns].sort((a, b) => a.order - b.order);
    for (const col of cols) {
      if (!col.name) continue;
      const typeStr = col.dataType.toUpperCase();
      const pkTag = col.primaryKey ? ' PK' : col.unique ? ' UK' : col.references ? ' FK' : '';
      lines.push(`    ${typeStr} ${col.name}${pkTag}`);
    }
    lines.push('  }');
    lines.push('');
  }

  // Relationships
  for (const entity of entities) {
    if (!entity.name) continue;
    for (const col of entity.columns) {
      if (col.references?.entityName) {
        lines.push(`  ${col.references.entityName} ||--o{ ${entity.name} : "has"`);
      }
    }
  }

  return lines.join('\n');
}

// ─── JSON Export ──────────────────────────────────────────────────────────────

function exportJson(entities: Entity[]): string {
  return JSON.stringify(entities, null, 2);
}

// ─── Sample INSERT Generation ─────────────────────────────────────────────────

function sampleValue(col: Column): string {
  if (col.defaultValue) return col.defaultValue;
  if (col.nullable) return 'NULL';
  switch (col.dataType) {
    case 'uuid': return `gen_random_uuid()`;
    case 'string': case 'varchar': case 'text': case 'char': return `'sample_${col.name}'`;
    case 'integer': case 'smallint': case 'bigint': case 'number': return '1';
    case 'float': case 'decimal': case 'numeric': return '1.0';
    case 'boolean': return 'true';
    case 'date': return `'2024-01-01'`;
    case 'datetime': case 'timestamp': case 'timestamptz': return `now()`;
    case 'time': return `'12:00:00'`;
    case 'json': case 'jsonb': return `'{}'`;
    case 'enum': return `'value'`;
    case 'array': return `'{}'`;
    default: return `'value'`;
  }
}

export function exportEntitySampleInsert(entity: Entity): string {
  const insertCols = entity.columns.filter((c) => !c.primaryKey || c.dataType !== 'uuid');
  if (insertCols.length === 0) return `-- No insertable columns on ${entity.name}`;
  const cols = insertCols.map((c) => c.name || 'column').join(', ');
  const vals = insertCols.map((c) => sampleValue(c)).join(', ');
  return `INSERT INTO ${entity.name} (${cols})\nVALUES (${vals});`;
}

// ─── Main Export Function ─────────────────────────────────────────────────────

export function exportEntityMarkdownTable(entity: Entity): string {
  const header = `### ${entity.name}\n`;
  const desc = entity.description ? `${entity.description}\n\n` : '';
  const tableHeader = '| Column | Type | PK | Nullable | Default | Note |\n| --- | --- | --- | --- | --- | --- |';
  const rows = entity.columns.map((col) =>
    `| ${col.name} | \`${col.dataType}\` | ${col.primaryKey ? '✓' : ''} | ${col.nullable ? '✓' : ''} | ${col.defaultValue || ''} | ${col.note || ''} |`
  ).join('\n');
  return header + desc + tableHeader + '\n' + rows;
}

// ─── Zod Schema Export ────────────────────────────────────────────────────────

function zodType(col: Column): string {
  let base: string;
  switch (col.dataType) {
    case 'uuid': base = 'z.string().uuid()'; break;
    case 'enum': {
      const vals = col.enumValues?.split(',').map((v) => v.trim()).filter(Boolean);
      base = vals && vals.length > 0 ? `z.enum([${vals.map((v) => `'${v}'`).join(', ')}])` : 'z.string()';
      break;
    }
    case 'string': case 'varchar': case 'text': case 'char': base = 'z.string()'; break;
    case 'integer': case 'smallint': case 'bigint': case 'number': base = 'z.number().int()'; break;
    case 'float': case 'decimal': case 'numeric': base = 'z.number()'; break;
    case 'boolean': base = 'z.boolean()'; break;
    case 'date': base = 'z.string().date()'; break;
    case 'datetime': case 'timestamp': case 'timestamptz': base = 'z.string().datetime()'; break;
    case 'time': base = 'z.string()'; break;
    case 'json': case 'jsonb': base = 'z.record(z.string(), z.unknown())'; break;
    case 'array': base = 'z.array(z.unknown())'; break;
    default: base = 'z.unknown()';
  }
  if (col.nullable) base += '.nullable()';
  if (col.nullable) base += '.optional()';
  return base;
}

export function exportEntityZodSchema(entity: Entity): string {
  const schemaName = toPascalCase(entity.name || 'Unknown') + 'Schema';
  const cols = [...entity.columns].sort((a, b) => a.order - b.order).filter((c) => c.name);
  const lines: string[] = [];
  lines.push(`import { z } from 'zod';`);
  lines.push('');
  if (entity.description) lines.push(`// ${entity.description}`);
  lines.push(`export const ${schemaName} = z.object({`);
  for (const col of cols) {
    const commentParts = [col.note, col.check?.trim() ? `CHECK: ${col.check.trim()}` : ''].filter(Boolean);
    const comment = commentParts.length > 0 ? ` // ${commentParts.join(' | ')}` : '';
    lines.push(`  ${col.name}: ${zodType(col)},${comment}`);
  }
  lines.push('});');
  lines.push('');
  lines.push(`export type ${toPascalCase(entity.name || 'Unknown')} = z.infer<typeof ${schemaName}>;`);
  return lines.join('\n');
}

function exportDbml(entities: Entity[]): string {
  const lines: string[] = [];
  lines.push('// Generated by surplan — https://dbdiagram.io compatible DBML');
  lines.push('');

  // Collect FK references to render as Ref blocks after tables
  const refs: string[] = [];

  for (const entity of entities) {
    lines.push(`Table ${entity.name} {`);

    for (const col of entity.columns) {
      let typeStr = col.dataType.toUpperCase();
      if (col.dataType === 'enum' && col.enumValues?.trim()) {
        typeStr = `varchar(50)`;
      }
      const settings: string[] = [];
      if (col.primaryKey) settings.push('pk');
      if (!col.nullable && !col.primaryKey) settings.push('not null');
      if (col.unique && !col.primaryKey) settings.push('unique');
      if (col.defaultValue) settings.push(`default: \`${col.defaultValue}\``);
      const noteText = [
        col.note,
        col.check ? `CHECK: ${col.check}` : '',
        col.indexed && !col.primaryKey ? 'indexed' : '',
      ].filter(Boolean).join(' | ');
      if (noteText) settings.push(`note: '${noteText.replace(/'/g, "\\'")}'`);

      const settingsStr = settings.length > 0 ? ` [${settings.join(', ')}]` : '';
      lines.push(`  ${col.name} ${typeStr}${settingsStr}`);

      if (col.references) {
        refs.push(`Ref: ${entity.name}.${col.name} > ${col.references.entityName}.${col.references.columnName}`);
      }
    }

    if (entity.description) {
      lines.push(`  Note: '${entity.description.replace(/'/g, "\\'")}'`);
    }

    // Indexes block for indexed/composite keys
    const indexedCols = entity.columns.filter((c) => c.indexed && !c.primaryKey && c.name);
    if (indexedCols.length > 0) {
      lines.push('');
      lines.push('  indexes {');
      for (const ic of indexedCols) {
        const indexAttr = ic.unique ? ' [unique]' : '';
        lines.push(`    ${ic.name}${indexAttr}`);
      }
      lines.push('  }');
    }

    lines.push('}');
    lines.push('');
  }

  if (refs.length > 0) {
    lines.push('// Relationships');
    refs.forEach((r) => lines.push(r));
  }

  return lines.join('\n').trimEnd();
}

// ─── Drizzle ORM Export ───────────────────────────────────────────────────────

function snakeToCamel(str: string): string {
  return str.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

function getDrizzleImportName(dataType: Column['dataType']): string | null {
  switch (dataType) {
    case 'uuid': return 'uuid';
    case 'varchar': case 'string': return 'varchar';
    case 'char': return 'char';
    case 'text': return 'text';
    case 'integer': case 'number': case 'smallint': return 'integer';
    case 'bigint': return 'bigint';
    case 'float': return 'real';
    case 'decimal': case 'numeric': return 'decimal';
    case 'boolean': return 'boolean';
    case 'date': return 'date';
    case 'datetime': case 'timestamp': case 'timestamptz': return 'timestamp';
    case 'time': return 'time';
    case 'json': return 'json';
    case 'jsonb': return 'jsonb';
    default: return 'text';
  }
}

function buildDrizzleColDef(col: Column, enumVarName: string | undefined): string {
  const name = col.name || 'column';
  let base: string;

  if (col.dataType === 'enum') {
    if (enumVarName) {
      base = `${enumVarName}('${name}')`;
    } else {
      base = `text('${name}') /* enum */`;
    }
  } else {
    switch (col.dataType) {
      case 'uuid': base = `uuid('${name}')`; break;
      case 'varchar': case 'string': base = `varchar('${name}', { length: 255 })`; break;
      case 'char': base = `char('${name}', { length: 1 })`; break;
      case 'text': base = `text('${name}')`; break;
      case 'integer': case 'number': case 'smallint': base = `integer('${name}')`; break;
      case 'bigint': base = `bigint('${name}', { mode: 'number' })`; break;
      case 'float': base = `real('${name}')`; break;
      case 'decimal': case 'numeric': base = `decimal('${name}', { precision: 10, scale: 2 })`; break;
      case 'boolean': base = `boolean('${name}')`; break;
      case 'date': base = `date('${name}')`; break;
      case 'datetime': case 'timestamp': base = `timestamp('${name}')`; break;
      case 'timestamptz': base = `timestamp('${name}', { withTimezone: true })`; break;
      case 'time': base = `time('${name}')`; break;
      case 'json': base = `json('${name}')`; break;
      case 'jsonb': base = `jsonb('${name}')`; break;
      case 'blob': case 'bytea': base = `text('${name}') /* bytea — use customType in production */`; break;
      case 'array': base = `json('${name}') /* array */`; break;
      default: base = `text('${name}')`;
    }
  }

  if (col.primaryKey) {
    base += '.primaryKey()';
    if (col.dataType === 'uuid') base += '.defaultRandom()';
  }
  if (!col.nullable && !col.primaryKey) base += '.notNull()';
  if (col.unique && !col.primaryKey) base += '.unique()';

  if (col.defaultValue && !col.primaryKey) {
    const dv = col.defaultValue.trim();
    if (dv === 'now()' || dv.toUpperCase() === 'CURRENT_TIMESTAMP') {
      base += '.defaultNow()';
    } else if (['integer', 'bigint', 'float', 'decimal', 'numeric', 'number', 'smallint'].includes(col.dataType)) {
      base += `.default(${dv})`;
    } else if (col.dataType === 'boolean') {
      base += `.default(${dv})`;
    } else if (/^\w+\s*\(/.test(dv)) {
      // SQL function call — requires sql template tag
      base += `.default(sql\`${dv}\`)`;
    } else {
      base += `.default('${dv.replace(/'/g, "\\'")}')`;
    }
  }

  if (col.references) {
    const refVar = snakeToCamel(col.references.entityName.toLowerCase());
    const refKey = snakeToCamel(col.references.columnName);
    base += `.references(() => ${refVar}.${refKey})`;
  }

  return base;
}

function exportDrizzle(entities: Entity[]): string {
  const lines: string[] = [];

  // Collect enum column defs: fingerprint -> { varName, dbTypeName, vals }
  const enumByFingerprint = new Map<string, { varName: string; dbTypeName: string; vals: string[] }>();
  const colToEnumVar = new Map<string, string>(); // `${entityId}:${colId}` -> varName

  entities.forEach((entity) => {
    entity.columns.forEach((col) => {
      if (col.dataType !== 'enum' || !col.enumValues?.trim()) return;
      const vals = col.enumValues.split(',').map((v) => v.trim()).filter(Boolean);
      const fingerprint = [...vals].sort().join('|');
      if (!enumByFingerprint.has(fingerprint)) {
        const varName = `${snakeToCamel(col.name)}Enum`;
        const dbTypeName = col.name.replace(/([A-Z])/g, '_$1').toLowerCase() + '_enum';
        enumByFingerprint.set(fingerprint, { varName, dbTypeName, vals });
      }
      colToEnumVar.set(`${entity.id}:${col.id}`, enumByFingerprint.get(fingerprint)!.varName);
    });
  });

  // Collect imports
  const usedImports = new Set<string>(['pgTable']);
  if (enumByFingerprint.size > 0) usedImports.add('pgEnum');
  let needsSqlTemplate = false;
  let hasCheckConstraints = false;
  entities.forEach((entity) => {
    entity.columns.forEach((col) => {
      if (col.dataType === 'enum') return; // enum handled by pgEnum
      const imp = getDrizzleImportName(col.dataType);
      if (imp) usedImports.add(imp);
      if (col.defaultValue && !col.primaryKey) {
        const dv = col.defaultValue.trim();
        if (/^\w+\s*\(/.test(dv) && dv.toLowerCase() !== 'now()' && dv.toUpperCase() !== 'CURRENT_TIMESTAMP') {
          needsSqlTemplate = true;
        }
      }
      if (col.check?.trim()) hasCheckConstraints = true;
    });
  });
  if (hasCheckConstraints) { usedImports.add('check'); needsSqlTemplate = true; }

  if (needsSqlTemplate) lines.push("import { sql } from 'drizzle-orm';");
  lines.push(`import { ${[...usedImports].sort().join(', ')} } from 'drizzle-orm/pg-core';`);
  lines.push('');
  lines.push('// Generated by surplan');
  lines.push(`// ${new Date().toISOString()}`);
  lines.push('');

  // Enum declarations
  enumByFingerprint.forEach(({ varName, dbTypeName, vals }) => {
    lines.push(`export const ${varName} = pgEnum('${dbTypeName}', [${vals.map((v) => `'${v}'`).join(', ')}]);`);
  });
  if (enumByFingerprint.size > 0) lines.push('');

  // Table declarations
  entities.forEach((entity) => {
    const tableVar = snakeToCamel(entity.name.toLowerCase());
    const tableName = entity.name;
    if (entity.description) lines.push(`// ${entity.description}`);
    lines.push(`export const ${tableVar} = pgTable('${tableName}', {`);
    entity.columns.forEach((col) => {
      const key = snakeToCamel(col.name) || col.name;
      const enumVar = colToEnumVar.get(`${entity.id}:${col.id}`);
      lines.push(`  ${key}: ${buildDrizzleColDef(col, enumVar)},`);
    });
    const checkCols = entity.columns.filter((c) => c.check?.trim() && c.name);
    if (checkCols.length > 0) {
      lines.push('}, (table) => [');
      checkCols.forEach((col) => {
        lines.push(`  check('chk_${tableName}_${col.name}', sql\`\${table.${snakeToCamel(col.name)}} ${col.check!.trim()}\`),`);
      });
      lines.push(']);');
    } else {
      lines.push('});');
    }
    lines.push('');
  });

  return lines.join('\n').trimEnd();
}

// ─── TypeORM Export ───────────────────────────────────────────────────────────

function toTypeOrmType(col: Column): string {
  switch (col.dataType) {
    case 'uuid': return 'uuid';
    case 'varchar': case 'string': return 'varchar';
    case 'char': return 'char';
    case 'text': return 'text';
    case 'integer': case 'number': return 'int';
    case 'smallint': return 'smallint';
    case 'bigint': return 'bigint';
    case 'float': return 'float';
    case 'decimal': case 'numeric': return 'decimal';
    case 'boolean': return 'boolean';
    case 'date': return 'date';
    case 'datetime': return 'datetime';
    case 'timestamp': return 'timestamp';
    case 'timestamptz': return 'timestamptz';
    case 'time': return 'time';
    case 'json': return 'json';
    case 'jsonb': return 'jsonb';
    case 'enum': return 'enum';
    case 'blob': case 'bytea': return 'bytea';
    default: return 'text';
  }
}

function toTsType(col: Column): string {
  switch (col.dataType) {
    case 'uuid': case 'varchar': case 'string': case 'char': case 'text': return 'string';
    case 'integer': case 'smallint': case 'float': case 'decimal': case 'numeric': case 'number': return 'number';
    case 'bigint': return 'bigint';
    case 'boolean': return 'boolean';
    case 'date': case 'datetime': case 'timestamp': case 'timestamptz': return 'Date';
    case 'time': return 'string';
    case 'json': case 'jsonb': return 'Record<string, unknown>';
    case 'enum': {
      if (col.enumValues?.trim()) {
        const vals = col.enumValues.split(',').map((v) => `'${v.trim()}'`).filter(Boolean);
        return vals.join(' | ');
      }
      return 'string';
    }
    case 'array': return 'unknown[]';
    default: return 'unknown';
  }
}

function buildTypeOrmColumn(col: Column): { decorator: string; propType: string } {
  const type = toTypeOrmType(col);
  const tsType = toTsType(col);
  const nullable = col.nullable ? ', nullable: true' : '';

  if (col.primaryKey) {
    if (col.dataType === 'uuid') {
      return { decorator: `@PrimaryGeneratedColumn('uuid')`, propType: tsType };
    }
    return { decorator: `@PrimaryGeneratedColumn()`, propType: tsType };
  }

  if (col.dataType === 'enum' && col.enumValues?.trim()) {
    const enumName = `${toPascalCase(col.name)}Enum`;
    const vals = col.enumValues.split(',').map((v) => v.trim()).filter(Boolean);
    const enumStr = vals.map((v) => `${v.toUpperCase().replace(/[^A-Z0-9_]/g, '_')}: '${v}'`).join(', ');
    const defaultStr = col.defaultValue ? `, default: '${col.defaultValue}'` : '';
    return {
      decorator: `// enum ${enumName} = { ${enumStr} }\n  @Column({ type: 'enum', enum: ${enumName}${defaultStr}${nullable} })`,
      propType: tsType,
    };
  }

  const opts: string[] = [`type: '${type}'`];
  if (col.unique) opts.push('unique: true');
  if (col.nullable) opts.push('nullable: true');
  if (col.defaultValue) {
    const dv = col.defaultValue.trim();
    const numTypes = ['integer', 'smallint', 'bigint', 'float', 'decimal', 'numeric', 'number'];
    if (numTypes.includes(col.dataType) || col.dataType === 'boolean') {
      opts.push(`default: ${dv}`);
    } else {
      opts.push(`default: '${dv}'`);
    }
  }

  const isCreatedAt = col.name === 'created_at' || col.name === 'createdAt';
  const isUpdatedAt = col.name === 'updated_at' || col.name === 'updatedAt';
  if (isCreatedAt && (col.dataType === 'timestamp' || col.dataType === 'timestamptz')) {
    return { decorator: '@CreateDateColumn()', propType: tsType };
  }
  if (isUpdatedAt && (col.dataType === 'timestamp' || col.dataType === 'timestamptz')) {
    return { decorator: '@UpdateDateColumn()', propType: tsType };
  }

  const optsStr = opts.length > 1 ? `{ ${opts.join(', ')} }` : `{ type: '${type}'${nullable} }`;
  return { decorator: `@Column(${optsStr})`, propType: tsType };
}

function exportTypeOrm(entities: Entity[]): string {
  const lines: string[] = [];

  // Collect needed imports
  const coreImports = new Set<string>(['Entity', 'Column']);
  entities.forEach((entity) => {
    entity.columns.forEach((col) => {
      if (col.primaryKey) {
        coreImports.add('PrimaryGeneratedColumn');
      }
      if ((col.name === 'created_at' || col.name === 'createdAt') && (col.dataType === 'timestamp' || col.dataType === 'timestamptz')) {
        coreImports.add('CreateDateColumn');
      }
      if ((col.name === 'updated_at' || col.name === 'updatedAt') && (col.dataType === 'timestamp' || col.dataType === 'timestamptz')) {
        coreImports.add('UpdateDateColumn');
      }
      if (col.references) {
        coreImports.add('ManyToOne');
        coreImports.add('JoinColumn');
      }
      if (col.check?.trim()) {
        coreImports.add('Check');
      }
    });
  });

  lines.push(`import { ${[...coreImports].sort().join(', ')} } from 'typeorm';`);
  lines.push('');
  lines.push('// Generated by surplan');
  lines.push(`// ${new Date().toISOString()}`);
  lines.push('');

  entities.forEach((entity) => {
    const className = toPascalCase(entity.name);
    if (entity.description) lines.push(`// ${entity.description}`);
    entity.columns.filter((c) => c.check?.trim() && c.name).forEach((col) => {
      lines.push(`@Check('chk_${entity.name}_${col.name}', '${col.check!.trim().replace(/'/g, "\\'")}')`);
    });
    lines.push(`@Entity('${entity.name}')`);
    lines.push(`export class ${className} {`);

    entity.columns.forEach((col) => {
      const key = snakeToCamel(col.name) || col.name;
      const { decorator, propType } = buildTypeOrmColumn(col);
      lines.push(`  ${decorator}`);
      const nullable = col.nullable && !col.primaryKey ? '?' : '!';
      lines.push(`  ${key}${nullable}: ${propType};`);
      lines.push('');
    });

    // FK relations
    entity.columns.forEach((col) => {
      if (!col.references) return;
      const refClass = toPascalCase(col.references.entityName);
      const propName = snakeToCamel(col.references.entityName.toLowerCase());
      lines.push(`  @ManyToOne(() => ${refClass}, { nullable: ${col.nullable} })`);
      lines.push(`  @JoinColumn({ name: '${col.name}' })`);
      lines.push(`  ${propName}!: ${refClass};`);
      lines.push('');
    });

    // Remove trailing blank line inside class
    if (lines[lines.length - 1] === '') lines.pop();
    lines.push('}');
    lines.push('');
  });

  return lines.join('\n').trimEnd();
}

function toGqlType(col: Column): string {
  let base: string;
  switch (col.dataType) {
    case 'integer':
    case 'bigint':
    case 'smallint':
    case 'number':
      base = 'Int'; break;
    case 'float':
    case 'decimal':
    case 'numeric':
      base = 'Float'; break;
    case 'boolean':
      base = 'Boolean'; break;
    case 'json':
    case 'jsonb':
      base = 'JSON'; break;
    case 'array':
      base = '[String]'; break;
    case 'enum':
      base = col.enumValues.trim() ? `${toPascalCase(col.name)}Enum` : 'String'; break;
    default:
      base = 'String';
  }
  if (col.primaryKey) base = 'ID';
  return col.nullable ? base : `${base}!`;
}

function exportGraphQL(entities: Entity[]): string {
  const lines: string[] = [];
  lines.push('# Generated by surplan');
  lines.push(`# ${new Date().toISOString()}`);
  lines.push('');

  const hasJson = entities.some((e) => e.columns.some((c) => c.dataType === 'json' || c.dataType === 'jsonb'));
  if (hasJson) { lines.push('scalar JSON'); lines.push(''); }

  // Collect + deduplicate enums
  const seenEnums = new Set<string>();
  entities.forEach((entity) => {
    entity.columns.forEach((col) => {
      if (col.dataType === 'enum' && col.enumValues.trim()) {
        const enumName = `${toPascalCase(col.name)}Enum`;
        if (!seenEnums.has(enumName)) {
          seenEnums.add(enumName);
          const values = col.enumValues.split(',')
            .map((v) => v.trim().toUpperCase().replace(/\W+/g, '_'))
            .filter(Boolean);
          lines.push(`enum ${enumName} {`);
          values.forEach((v) => lines.push(`  ${v}`));
          lines.push('}');
          lines.push('');
        }
      }
    });
  });

  // Types
  entities.forEach((entity) => {
    const typeName = toPascalCase(entity.name);
    if (entity.description) lines.push(`"""${entity.description}"""`);
    lines.push(`type ${typeName} {`);
    entity.columns.forEach((col) => {
      const fieldName = snakeToCamel(col.name) || col.name;
      const note = col.note ? ` # ${col.note}` : '';
      lines.push(`  ${fieldName}: ${toGqlType(col)}${note}`);
    });
    // Relation fields for FK columns
    entity.columns.forEach((col) => {
      if (col.references) {
        const refType = toPascalCase(col.references.entityName);
        const relField = snakeToCamel(col.references.entityName.toLowerCase());
        lines.push(`  ${relField}: ${refType}${col.nullable ? '' : '!'}`);
      }
    });
    lines.push('}');
    lines.push('');
  });

  // Input types
  entities.forEach((entity) => {
    const typeName = toPascalCase(entity.name);
    const inputCols = entity.columns.filter((c) => !c.primaryKey);
    if (inputCols.length === 0) return;
    lines.push(`input Create${typeName}Input {`);
    inputCols.forEach((col) => {
      const fieldName = snakeToCamel(col.name) || col.name;
      lines.push(`  ${fieldName}: ${toGqlType(col)}`);
    });
    lines.push('}');
    lines.push('');
    lines.push(`input Update${typeName}Input {`);
    inputCols.forEach((col) => {
      const fieldName = snakeToCamel(col.name) || col.name;
      const t = toGqlType(col);
      const optional = t.endsWith('!') ? t.slice(0, -1) : t;
      lines.push(`  ${fieldName}: ${optional}`);
    });
    lines.push('}');
    lines.push('');
  });

  // Query + Mutation roots
  if (entities.length > 0) {
    lines.push('type Query {');
    entities.forEach((entity) => {
      const typeName = toPascalCase(entity.name);
      const plural = `${snakeToCamel(entity.name)}s`;
      const singular = snakeToCamel(entity.name);
      lines.push(`  ${singular}(id: ID!): ${typeName}`);
      lines.push(`  ${plural}: [${typeName}!]!`);
    });
    lines.push('}');
    lines.push('');
    lines.push('type Mutation {');
    entities.forEach((entity) => {
      const typeName = toPascalCase(entity.name);
      lines.push(`  create${typeName}(input: Create${typeName}Input!): ${typeName}!`);
      lines.push(`  update${typeName}(id: ID!, input: Update${typeName}Input!): ${typeName}`);
      lines.push(`  delete${typeName}(id: ID!): Boolean!`);
    });
    lines.push('}');
  }

  return lines.join('\n').trimEnd();
}

// ─── Sequelize Export ──────────────────────────────────────────────────────────

function toSequelizeType(col: Column): string {
  switch (col.dataType) {
    case 'uuid': return 'DataTypes.UUID';
    case 'string': case 'varchar': return 'DataTypes.STRING';
    case 'char': return 'DataTypes.CHAR';
    case 'text': return 'DataTypes.TEXT';
    case 'integer': case 'number': return 'DataTypes.INTEGER';
    case 'smallint': return 'DataTypes.SMALLINT';
    case 'bigint': return 'DataTypes.BIGINT';
    case 'float': return 'DataTypes.FLOAT';
    case 'decimal': case 'numeric': return 'DataTypes.DECIMAL';
    case 'boolean': return 'DataTypes.BOOLEAN';
    case 'date': return 'DataTypes.DATEONLY';
    case 'datetime': case 'timestamp': case 'timestamptz': return 'DataTypes.DATE';
    case 'time': return 'DataTypes.TIME';
    case 'json': case 'jsonb': return 'DataTypes.JSON';
    case 'enum': {
      const vals = col.enumValues?.split(',').map((v) => `'${v.trim()}'`).filter(Boolean);
      return vals && vals.length > 0 ? `DataTypes.ENUM(${vals.join(', ')})` : 'DataTypes.STRING';
    }
    case 'blob': case 'bytea': return 'DataTypes.BLOB';
    case 'array': return 'DataTypes.ARRAY(DataTypes.TEXT)';
    default: return 'DataTypes.STRING';
  }
}

function exportSequelize(entities: Entity[]): string {
  const lines: string[] = [];
  lines.push(`import { DataTypes, Model, InferAttributes, InferCreationAttributes, CreationOptional, Sequelize } from 'sequelize';`);
  lines.push('');
  lines.push('// Generated by surplan');
  lines.push(`// ${new Date().toISOString()}`);
  lines.push('');
  lines.push(`const sequelize = new Sequelize(process.env.DATABASE_URL ?? 'sqlite::memory:');`);
  lines.push('');

  for (const entity of entities) {
    if (!entity.name) continue;
    const className = toPascalCase(entity.name);
    const cols = [...entity.columns].sort((a, b) => a.order - b.order).filter((c) => c.name);

    lines.push(`// ─── ${entity.name} ──────────────────────────────────────────`);
    if (entity.description) lines.push(`// ${entity.description}`);
    lines.push('');
    lines.push(`export class ${className} extends Model<`);
    lines.push(`  InferAttributes<${className}>,`);
    lines.push(`  InferCreationAttributes<${className}>`);
    lines.push(`> {`);

    for (const col of cols) {
      const t = tsType(col);
      if (col.nullable || col.primaryKey) {
        lines.push(`  declare ${col.name}: CreationOptional<${t}>;`);
      } else {
        lines.push(`  declare ${col.name}: ${t};`);
      }
    }

    lines.push('}');
    lines.push('');
    lines.push(`${className}.init(`);
    lines.push('  {');

    for (const col of cols) {
      const parts: string[] = [`type: ${toSequelizeType(col)}`];
      if (col.primaryKey) parts.push('primaryKey: true');
      if (col.dataType === 'uuid' && col.primaryKey) parts.push('defaultValue: DataTypes.UUIDV4');
      if (!col.nullable && !col.primaryKey) parts.push('allowNull: false');
      if (col.nullable) parts.push('allowNull: true');
      if (col.unique) parts.push('unique: true');
      if (col.defaultValue) {
        const isStr = ['string', 'varchar', 'text', 'char', 'uuid', 'enum'].includes(col.dataType);
        parts.push(`defaultValue: ${isStr ? `'${col.defaultValue}'` : col.defaultValue}`);
      }
      if (col.references) {
        parts.push(`references: { model: '${col.references.entityName}', key: '${col.references.columnName}' }`);
      }
      lines.push(`    ${col.name}: { ${parts.join(', ')} },`);
    }

    lines.push('  },');
    lines.push('  {');
    lines.push(`    tableName: '${entity.name}',`);
    lines.push('    sequelize,');
    lines.push('  }');
    lines.push(');');
    lines.push('');
  }

  return lines.join('\n').trimEnd();
}

// ─── Mongoose Export ───────────────────────────────────────────────────────────

function toMongooseType(col: Column): string {
  switch (col.dataType) {
    case 'uuid': case 'string': case 'varchar': case 'text': case 'char': return 'String';
    case 'integer': case 'smallint': case 'bigint': case 'float': case 'decimal': case 'numeric': case 'number': return 'Number';
    case 'boolean': return 'Boolean';
    case 'date': case 'datetime': case 'timestamp': case 'timestamptz': return 'Date';
    case 'time': return 'String';
    case 'json': case 'jsonb': return 'Schema.Types.Mixed';
    case 'array': return '[Schema.Types.Mixed]';
    case 'blob': case 'bytea': return 'Buffer';
    case 'enum': return 'String';
    default: return 'String';
  }
}

function exportMongoose(entities: Entity[]): string {
  const lines: string[] = [];
  lines.push(`import { Schema, model } from 'mongoose';`);
  lines.push('');
  lines.push('// Generated by surplan');
  lines.push(`// ${new Date().toISOString()}`);
  lines.push('');

  for (const entity of entities) {
    if (!entity.name) continue;
    const className = toPascalCase(entity.name);
    const cols = [...entity.columns].sort((a, b) => a.order - b.order).filter((c) => c.name);
    const dataCols = cols.filter((c) => !c.primaryKey);

    lines.push(`// ─── ${entity.name} ──────────────────────────────────────────`);
    if (entity.description) lines.push(`// ${entity.description}`);
    lines.push('');
    lines.push(`export interface I${className} {`);
    for (const col of dataCols) {
      lines.push(`  ${col.name}${col.nullable ? '?' : ''}: ${tsType(col)};`);
    }
    lines.push('}');
    lines.push('');
    lines.push(`const ${entity.name}Schema = new Schema<I${className}>({`);

    for (const col of dataCols) {
      const parts: string[] = [];
      if (col.references) {
        parts.push('type: Schema.Types.ObjectId');
        parts.push(`ref: '${toPascalCase(col.references.entityName)}'`);
      } else {
        parts.push(`type: ${toMongooseType(col)}`);
      }
      if (!col.nullable) parts.push('required: true');
      if (col.unique) parts.push('unique: true');
      if (col.indexed && !col.unique) parts.push('index: true');
      if (col.defaultValue) {
        const isStr = ['string', 'varchar', 'text', 'char', 'uuid', 'enum'].includes(col.dataType);
        parts.push(`default: ${isStr ? `'${col.defaultValue}'` : col.defaultValue}`);
      }
      if (col.dataType === 'enum' && col.enumValues) {
        const vals = col.enumValues.split(',').map((v) => `'${v.trim()}'`).filter(Boolean);
        if (vals.length > 0) parts.push(`enum: [${vals.join(', ')}]`);
      }
      lines.push(`  ${col.name}: { ${parts.join(', ')} },`);
    }

    lines.push('}, { timestamps: true });');
    lines.push('');
    lines.push(`export const ${className} = model<I${className}>('${className}', ${entity.name}Schema);`);
    lines.push('');
  }

  return lines.join('\n').trimEnd();
}

// ─── SQLAlchemy Export ─────────────────────────────────────────────────────────

function toSaType(col: Column): string {
  switch (col.dataType) {
    case 'uuid': return 'Uuid';
    case 'string': case 'varchar': return 'String';
    case 'char': return 'String(1)';
    case 'text': return 'Text';
    case 'integer': case 'number': case 'smallint': return 'Integer';
    case 'bigint': return 'BigInteger';
    case 'float': return 'Float';
    case 'decimal': case 'numeric': return 'Numeric';
    case 'boolean': return 'Boolean';
    case 'date': return 'Date';
    case 'datetime': case 'timestamp': return 'DateTime';
    case 'timestamptz': return 'DateTime(timezone=True)';
    case 'time': return 'Time';
    case 'json': case 'jsonb': return 'JSON';
    case 'enum': {
      const vals = col.enumValues?.split(',').map((v) => `'${v.trim()}'`).filter(Boolean);
      return vals && vals.length > 0 ? `Enum(${vals.join(', ')})` : 'String';
    }
    case 'blob': case 'bytea': return 'LargeBinary';
    case 'array': return 'ARRAY(Text)';
    default: return 'String';
  }
}

function toPythonType(col: Column): string {
  switch (col.dataType) {
    case 'uuid': return 'uuid_lib.UUID';
    case 'string': case 'varchar': case 'text': case 'char': case 'time': case 'enum': return 'str';
    case 'integer': case 'smallint': case 'bigint': case 'number': return 'int';
    case 'float': case 'decimal': case 'numeric': return 'float';
    case 'boolean': return 'bool';
    case 'date': return 'date';
    case 'datetime': case 'timestamp': case 'timestamptz': return 'datetime';
    case 'json': case 'jsonb': return 'dict';
    case 'array': return 'list';
    case 'blob': case 'bytea': return 'bytes';
    default: return 'str';
  }
}

function exportSqlAlchemy(entities: Entity[]): string {
  const usesUuid = entities.some((e) => e.columns.some((c) => c.dataType === 'uuid'));
  const usesDatetime = entities.some((e) => e.columns.some((c) => ['datetime', 'timestamp', 'timestamptz'].includes(c.dataType)));
  const usesDate = entities.some((e) => e.columns.some((c) => c.dataType === 'date'));
  const usesBigint = entities.some((e) => e.columns.some((c) => c.dataType === 'bigint'));
  const usesArray = entities.some((e) => e.columns.some((c) => c.dataType === 'array'));
  const usesEnum = entities.some((e) => e.columns.some((c) => c.dataType === 'enum'));

  const lines: string[] = [];
  lines.push('# Generated by surplan');
  lines.push(`# ${new Date().toISOString()}`);
  lines.push('');
  lines.push('from __future__ import annotations');
  lines.push('');
  const pyImports: string[] = ['Optional'];
  if (usesDatetime) pyImports.push('datetime');
  if (usesDate) pyImports.push('date');
  lines.push(`from typing import ${pyImports.join(', ')}`);
  if (usesUuid) lines.push('import uuid as uuid_lib');
  lines.push('');

  const usesCheck = entities.some((e) => e.columns.some((c) => c.check?.trim()));
  const saTypes = new Set(['Column', 'ForeignKey', 'String', 'Integer', 'Text', 'Boolean', 'Float', 'Numeric', 'JSON']);
  if (usesUuid) saTypes.add('Uuid');
  if (usesDatetime) saTypes.add('DateTime');
  if (usesDate) { saTypes.add('Date'); saTypes.add('Time'); }
  if (usesBigint) saTypes.add('BigInteger');
  if (usesArray) saTypes.add('ARRAY');
  if (usesEnum) saTypes.add('Enum');
  if (usesCheck) saTypes.add('CheckConstraint');
  lines.push(`from sqlalchemy import ${[...saTypes].join(', ')}`);
  lines.push('from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship');
  lines.push('');
  lines.push('');
  lines.push('class Base(DeclarativeBase):');
  lines.push('    pass');
  lines.push('');
  lines.push('');

  for (const entity of entities) {
    if (!entity.name) continue;
    const className = toPascalCase(entity.name);
    const cols = [...entity.columns].sort((a, b) => a.order - b.order).filter((c) => c.name);

    if (entity.description) lines.push(`# ${entity.description}`);
    lines.push(`class ${className}(Base):`);
    lines.push(`    __tablename__ = "${entity.name}"`);
    const checkCols = cols.filter((c) => c.check?.trim());
    if (checkCols.length > 0) {
      const constraintArgs = checkCols.map((c) => `CheckConstraint("${c.check!.trim()}", name="chk_${entity.name}_${c.name}")`).join(', ');
      lines.push(`    __table_args__ = (${constraintArgs},)`);
    }
    lines.push('');

    for (const col of cols) {
      const saT = toSaType(col);
      const pyT = toPythonType(col);
      const parts: string[] = [saT];
      if (col.primaryKey) parts.push('primary_key=True');
      if (!col.nullable && !col.primaryKey) parts.push('nullable=False');
      if (col.nullable) parts.push('nullable=True');
      if (col.unique) parts.push('unique=True');
      if (col.indexed && !col.primaryKey) parts.push('index=True');
      if (col.defaultValue) {
        parts.push(`server_default="${col.defaultValue}"`);
      }
      if (col.references) {
        parts.push(`ForeignKey("${col.references.entityName}.${col.references.columnName}")`);
      }
      const mappedT = col.nullable ? `Optional[${pyT}]` : pyT;
      lines.push(`    ${col.name}: Mapped[${mappedT}] = mapped_column(${parts.join(', ')})`);
    }

    const fkCols = cols.filter((c) => c.references);
    if (fkCols.length > 0) {
      lines.push('');
      for (const col of fkCols) {
        const relName = col.references!.entityName;
        const relClass = toPascalCase(relName);
        lines.push(`    ${relName}: Mapped[Optional["${relClass}"]] = relationship("${relClass}")`);
      }
    }

    lines.push('');
    lines.push('');
  }

  return lines.join('\n').trimEnd();
}

function jsonSchemaType(col: Column): Record<string, unknown> {
  const dt = col.dataType;
  let base: Record<string, unknown>;
  if (dt === 'uuid') base = { type: 'string', format: 'uuid' };
  else if (dt === 'string' || dt === 'varchar' || dt === 'text' || dt === 'char') base = { type: 'string' };
  else if (dt === 'integer' || dt === 'bigint' || dt === 'smallint') base = { type: 'integer' };
  else if (dt === 'float' || dt === 'decimal' || dt === 'numeric' || dt === 'number') base = { type: 'number' };
  else if (dt === 'boolean') base = { type: 'boolean' };
  else if (dt === 'date') base = { type: 'string', format: 'date' };
  else if (dt === 'datetime' || dt === 'timestamp' || dt === 'timestamptz') base = { type: 'string', format: 'date-time' };
  else if (dt === 'time') base = { type: 'string', format: 'time' };
  else if (dt === 'json' || dt === 'jsonb') base = {};
  else if (dt === 'enum') {
    const values = col.enumValues ? col.enumValues.split(',').map((v) => v.trim()).filter(Boolean) : [];
    base = values.length > 0 ? { enum: values } : { type: 'string' };
  } else if (dt === 'blob' || dt === 'bytea') base = { type: 'string', contentEncoding: 'base64' };
  else if (dt === 'array') base = { type: 'array' };
  else base = { type: 'string' };

  if (col.nullable) {
    if (base.type) return { ...base, type: [base.type, 'null'] };
    return { oneOf: [base, { type: 'null' }] };
  }
  return base;
}

function exportJsonSchema(entities: Entity[]): string {
  const definitions: Record<string, unknown> = {};
  for (const entity of entities) {
    const required: string[] = [];
    const properties: Record<string, unknown> = {};
    for (const col of [...entity.columns].sort((a, b) => a.order - b.order)) {
      const propSchema: Record<string, unknown> = { ...jsonSchemaType(col) };
      if (col.note) propSchema.description = col.note;
      if (col.defaultValue) propSchema.default = col.defaultValue;
      properties[col.name || `col_${col.id.slice(0, 6)}`] = propSchema;
      if (!col.nullable && !col.defaultValue) required.push(col.name || `col_${col.id.slice(0, 6)}`);
    }
    const schema: Record<string, unknown> = {
      type: 'object',
      properties,
    };
    if (required.length > 0) schema.required = required;
    if (entity.description) schema.description = entity.description;
    definitions[entity.name] = schema;
  }
  return JSON.stringify({
    $schema: 'http://json-schema.org/draft-07/schema#',
    title: 'Generated by surplan',
    definitions,
  }, null, 2);
}

export function exportEntities(entities: Entity[], format: ExportFormat): string {
  switch (format) {
    case 'sql-postgres': return exportSql(entities, 'postgres');
    case 'sql-mysql': return exportSql(entities, 'mysql');
    case 'sql-sqlite': return exportSql(entities, 'sqlite');
    case 'typescript': return exportTypeScript(entities);
    case 'zod': return exportAllZodSchemas(entities);
    case 'prisma': return exportPrisma(entities);
    case 'drizzle': return exportDrizzle(entities);
    case 'typeorm': return exportTypeOrm(entities);
    case 'mermaid': return exportMermaid(entities);
    case 'json': return exportJson(entities);
    case 'dbml': return exportDbml(entities);
    case 'graphql': return exportGraphQL(entities);
    case 'sequelize': return exportSequelize(entities);
    case 'mongoose': return exportMongoose(entities);
    case 'sqlalchemy': return exportSqlAlchemy(entities);
    case 'jsonschema': return exportJsonSchema(entities);
    case 'knex': return exportKnex(entities);
    case 'mikro-orm': return exportMikroOrm(entities);
    default: return '';
  }
}

function exportAllZodSchemas(entities: Entity[]): string {
  const lines: string[] = [];
  lines.push(`import { z } from 'zod';`);
  lines.push('');
  lines.push('// Generated by surplan');
  lines.push(`// ${new Date().toISOString()}`);
  lines.push('');
  for (const entity of entities) {
    // Skip the import line since we already have it
    const schema = exportEntityZodSchema(entity)
      .replace(/^import \{ z \} from 'zod';\n\n/, '')
      .trimStart();
    lines.push(schema);
    lines.push('');
  }
  return lines.join('\n').trimEnd();
}

// ─── Knex.js Migration Export ─────────────────────────────────────────────────

function toKnexType(col: Column): string {
  switch (col.dataType) {
    case 'uuid': return 'uuid';
    case 'string': case 'varchar': case 'char': return 'string';
    case 'text': return 'text';
    case 'integer': case 'number': case 'smallint': return 'integer';
    case 'bigint': return 'bigint';
    case 'float': return 'float';
    case 'decimal': case 'numeric': return 'decimal';
    case 'boolean': return 'boolean';
    case 'date': return 'date';
    case 'datetime': case 'timestamp': case 'timestamptz': return 'timestamp';
    case 'time': return 'time';
    case 'json': return 'json';
    case 'jsonb': return 'jsonb';
    case 'enum': return 'enu';
    case 'blob': case 'bytea': return 'binary';
    case 'array': return 'specificType';
    default: return 'string';
  }
}

function exportKnex(entities: Entity[]): string {
  const lines: string[] = [];
  lines.push('// Generated by surplan');
  lines.push(`// ${new Date().toISOString()}`);
  lines.push('// Run with: knex migrate:latest');
  lines.push('');
  lines.push("/** @param { import('knex').Knex } knex */");
  lines.push('exports.up = async function (knex) {');

  for (const entity of entities) {
    const table = entity.name || 'unnamed';
    const cols = [...entity.columns].sort((a, b) => a.order - b.order).filter((c) => c.name);
    if (cols.length === 0) continue;
    if (entity.description) lines.push(`  // ${entity.description}`);
    lines.push(`  await knex.schema.createTable('${table}', (t) => {`);
    for (const col of cols) {
      const knexType = toKnexType(col);
      let chain = '    t';
      if (col.primaryKey && col.dataType === 'uuid') {
        chain += `.uuid('${col.name}').primary()`;
      } else if (col.primaryKey && ['integer', 'number', 'bigint', 'smallint'].includes(col.dataType)) {
        chain += `.increments('${col.name}')`;
      } else if (knexType === 'enu') {
        const vals = (col.enumValues ?? '').split(',').map((v) => `'${v.trim()}'`).filter(Boolean).join(', ');
        chain += `.enu('${col.name}', [${vals}])`;
      } else if (col.dataType === 'array') {
        chain += `.specificType('${col.name}', 'text[]')`;
      } else if (knexType === 'decimal') {
        chain += `.decimal('${col.name}', 10, 2)`;
      } else {
        chain += `.${knexType}('${col.name}')`;
      }
      if (!col.primaryKey) {
        chain += col.nullable ? '.nullable()' : '.notNullable()';
      }
      if (col.unique && !col.primaryKey) chain += '.unique()';
      if (col.defaultValue) {
        const isSqlExpr = /^\s*(\w+\s*\(|\d|true$|false$|null$)/i.test(col.defaultValue.trim());
        chain += `.defaultTo(${isSqlExpr ? col.defaultValue : `'${col.defaultValue}'`})`;
      }
      if (col.references?.entityName && col.references?.columnName) {
        chain += `.references('${col.references.columnName}').inTable('${col.references.entityName}').onDelete('SET NULL').onUpdate('CASCADE')`;
      }
      if (col.indexed && !col.primaryKey && !col.unique) chain += '.index()';
      chain += ';';
      if (col.note) chain += ` // ${col.note}`;
      lines.push(chain);
    }
    lines.push('  });');
    lines.push('');
  }

  lines.push('};');
  lines.push('');
  lines.push("/** @param { import('knex').Knex } knex */");
  lines.push('exports.down = async function (knex) {');
  [...entities].reverse().forEach((entity) => {
    if (entity.name) lines.push(`  await knex.schema.dropTableIfExists('${entity.name}');`);
  });
  lines.push('};');
  return lines.join('\n');
}

// ─── MikroORM Export ──────────────────────────────────────────────────────────

function toMikroOrmTsType(col: Column): string {
  switch (col.dataType) {
    case 'integer': case 'smallint': case 'bigint': case 'float': case 'decimal': case 'numeric': case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'date': case 'datetime': case 'timestamp': case 'timestamptz': return 'Date';
    case 'json': case 'jsonb': return 'Record<string, unknown>';
    case 'array': return 'string[]';
    case 'enum': return col.enumValues?.trim() ? `${toPascalCase(col.name)}Enum` : 'string';
    default: return 'string';
  }
}

function exportMikroOrm(entities: Entity[]): string {
  const lines: string[] = [];
  lines.push('// Generated by surplan');
  lines.push(`// ${new Date().toISOString()}`);
  lines.push("import { Entity, PrimaryKey, Property, ManyToOne, OneToMany, Enum, Collection, Cascade } from '@mikro-orm/core';");
  lines.push('');

  const enumsEmitted = new Set<string>();
  entities.forEach((entity) => {
    entity.columns.forEach((col) => {
      if (col.dataType === 'enum' && col.enumValues?.trim()) {
        const enumName = `${toPascalCase(col.name)}Enum`;
        if (!enumsEmitted.has(enumName)) {
          enumsEmitted.add(enumName);
          const vals = col.enumValues.split(',').map((v) => v.trim()).filter(Boolean);
          lines.push(`export enum ${enumName} {`);
          vals.forEach((v) => lines.push(`  ${v.toUpperCase().replace(/\W+/g, '_')} = '${v}',`));
          lines.push('}');
          lines.push('');
        }
      }
    });
  });

  entities.forEach((entity) => {
    const className = toPascalCase(entity.name);
    const cols = [...entity.columns].sort((a, b) => a.order - b.order).filter((c) => c.name);
    if (entity.description) lines.push(`/** ${entity.description} */`);
    lines.push(`@Entity({ tableName: '${entity.name}' })`);
    lines.push(`export class ${className} {`);

    for (const col of cols) {
      const fieldName = snakeToCamel(col.name);
      const tsType = toMikroOrmTsType(col);
      const nullOpt = col.nullable ? ', nullable: true' : '';

      if (col.primaryKey) {
        if (col.dataType === 'uuid') {
          lines.push(`  @PrimaryKey({ type: 'uuid' })`);
        } else {
          lines.push(`  @PrimaryKey()`);
        }
        lines.push(`  ${fieldName}!: ${tsType};`);
      } else if (col.references) {
        const refClass = toPascalCase(col.references.entityName);
        const refField = snakeToCamel(col.references.entityName);
        lines.push(`  @ManyToOne(() => ${refClass}${col.nullable ? ', { nullable: true }' : ''})`);
        lines.push(`  ${refField}!: ${refClass};`);
      } else if (col.dataType === 'enum' && col.enumValues?.trim()) {
        const enumName = `${toPascalCase(col.name)}Enum`;
        lines.push(`  @Enum({ items: () => ${enumName}${nullOpt} })`);
        lines.push(`  ${fieldName}!: ${enumName};`);
      } else {
        const defaultPart = col.defaultValue ? `, default: ${/^\d+$/.test(col.defaultValue) ? col.defaultValue : `'${col.defaultValue}'`}` : '';
        lines.push(`  @Property({ columnType: '${col.dataType}'${nullOpt}${defaultPart} })`);
        lines.push(`  ${fieldName}!: ${tsType}${col.nullable ? ' | null' : ''};`);
      }
    }

    entities.forEach((other) => {
      if (other.id === entity.id) return;
      other.columns.forEach((col) => {
        if (col.references?.entityId === entity.id && col.name) {
          const otherClass = toPascalCase(other.name);
          const collField = snakeToCamel(other.name) + 's';
          const ownField = snakeToCamel(col.name.replace(/_id$/i, '')) || snakeToCamel(entity.name);
          lines.push(`  @OneToMany(() => ${otherClass}, (x) => x.${ownField}, { cascade: [Cascade.ALL] })`);
          lines.push(`  ${collField} = new Collection<${otherClass}>(this);`);
        }
      });
    });

    lines.push('}');
    lines.push('');
  });

  return lines.join('\n').trimEnd();
}

// ─── Frontend Exports ──────────────────────────────────────────────────────

export function exportFrontend(format: FrontendExportFormat, pages: Page[], components: UIComponent[], tokens: DesignTokens, entities: Entity[]): string {
  switch (format) {
    case 'react': return exportReactComponents(components, entities);
    case 'nextjs': return exportNextPages(pages, components);
    case 'css-tokens': return exportCssTokens(tokens);
    case 'tailwind-config': return exportTailwindConfig(tokens);
    case 'component-docs': return exportComponentDocs(components, pages);
    case 'mermaid-sitemap': return exportMermaidSitemap(pages);
    default: return '';
  }
}

function exportReactComponents(components: UIComponent[], _entities: Entity[]): string {
  const lines: string[] = [];
  lines.push('// Auto-generated React component stubs from surplan');
  lines.push('');

  for (const comp of components) {
    if (comp.props.length > 0) {
      lines.push(`interface ${comp.name}Props {`);
      for (const p of comp.props) {
        const opt = p.required ? '' : '?';
        lines.push(`  ${p.name}${opt}: ${p.type || 'unknown'};${p.description ? ` // ${p.description}` : ''}`);
      }
      lines.push('}');
      lines.push('');
    }

    const propsParam = comp.props.length > 0 ? `{ ${comp.props.map((p) => p.name).join(', ')} }: ${comp.name}Props` : '';
    lines.push(`export function ${comp.name}(${propsParam}) {`);

    for (const sf of comp.stateFields) {
      const init = sf.initialValue || (sf.type === 'boolean' ? 'false' : sf.type === 'number' ? '0' : "''");
      lines.push(`  const [${sf.name}, set${sf.name.charAt(0).toUpperCase() + sf.name.slice(1)}] = useState<${sf.type || 'unknown'}>(${init});`);
    }
    if (comp.stateFields.length > 0) lines.push('');

    for (const ev of comp.events) {
      const payload = ev.payload && ev.payload !== 'void' ? `_payload: ${ev.payload}` : '';
      lines.push(`  const ${ev.name} = (${payload}) => {`);
      lines.push(`    // TODO: implement ${ev.name}`);
      lines.push('  };');
      lines.push('');
    }

    lines.push('  return (');
    lines.push(`    <div className="${comp.kind}">`);
    lines.push(`      {/* TODO: implement ${comp.name} */}`);
    if (comp.children.length > 0) {
      for (const cid of comp.children) {
        const child = components.find((c) => c.id === cid);
        if (child) lines.push(`      <${child.name} />`);
      }
    }
    lines.push('    </div>');
    lines.push('  );');
    lines.push('}');
    lines.push('');
  }

  if (components.some((c) => c.stateFields.length > 0)) {
    lines.unshift("import { useState } from 'react';");
    lines.splice(1, 0, '');
  }

  return lines.join('\n').trimEnd() || '// No components defined yet';
}

function exportNextPages(pages: Page[], components: UIComponent[]): string {
  const lines: string[] = [];
  lines.push('// Auto-generated Next.js App Router pages from surplan');
  lines.push('');

  for (const page of pages) {
    const appPath = page.path.replace(/^\//, '').replace(/:(\w+)/g, '[$1]').replace(/\/$/, '') || '(root)';
    lines.push(`// ═══ app/${appPath}/page.tsx ═══`);
    lines.push('');

    const params = (page.path.match(/:(\w+)/g) || []).map((p) => p.slice(1));
    if (params.length > 0) {
      lines.push(`interface PageProps { params: { ${params.map((p) => `${p}: string`).join('; ')} } }`);
      lines.push('');
    }

    const propsParam = params.length > 0 ? `{ params }: PageProps` : '';
    const isAsync = page.dataBindings.length > 0;
    lines.push(`export default ${isAsync ? 'async ' : ''}function ${page.name.replace(/[^a-zA-Z0-9]/g, '')}Page(${propsParam}) {`);

    if (isAsync) {
      for (const db of page.dataBindings) lines.push(`  // TODO: fetch — ${db.description || db.endpointId}`);
      lines.push('');
    }

    lines.push('  return (');
    lines.push(`    <div className="layout-${page.layout}">`);

    if (page.wireframeSections.length > 0) {
      for (const ws of [...page.wireframeSections].sort((a, b) => a.order - b.order)) {
        const comp = components.find((c) => c.id === ws.componentRef);
        lines.push(comp ? `      <${comp.name} /> {/* ${ws.label} */}` : `      <section>{/* ${ws.label} (${ws.width}) */}</section>`);
      }
    } else {
      const pageComps = components.filter((c) => page.componentRefs.includes(c.id));
      for (const c of pageComps) lines.push(`      <${c.name} />`);
      if (pageComps.length === 0) lines.push(`      {/* TODO: ${page.name} */}`);
    }

    lines.push('    </div>');
    lines.push('  );');
    lines.push('}');

    if (page.metaTitle || page.metaDescription) {
      lines.push('');
      lines.push(`export const metadata = {${page.metaTitle ? ` title: '${page.metaTitle.replace(/'/g, "\\'")}',` : ''}${page.metaDescription ? ` description: '${page.metaDescription.replace(/'/g, "\\'")}',` : ''} };`);
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() || '// No pages defined yet';
}

function exportCssTokens(tokens: DesignTokens): string {
  const lines: string[] = [];
  lines.push('/* Auto-generated CSS custom properties from surplan */');
  lines.push(':root {');
  if (tokens.colors.length > 0) {
    lines.push('  /* Colors */');
    for (const c of tokens.colors) if (c.name) lines.push(`  --color-${c.name}: ${c.value};`);
  }
  if (tokens.typography.length > 0) {
    lines.push('  /* Typography */');
    for (const t of tokens.typography) {
      if (!t.name) continue;
      lines.push(`  --font-size-${t.name}: ${t.fontSize};`);
      lines.push(`  --font-weight-${t.name}: ${t.fontWeight};`);
      lines.push(`  --line-height-${t.name}: ${t.lineHeight};`);
    }
  }
  if (tokens.spacing.length > 0) {
    lines.push('  /* Spacing */');
    for (const s of tokens.spacing) if (s.name) lines.push(`  --spacing-${s.name}: ${s.value};`);
  }
  if (tokens.breakpoints.length > 0) {
    lines.push('  /* Breakpoints */');
    for (const b of tokens.breakpoints) if (b.name) lines.push(`  --breakpoint-${b.name}: ${b.value};`);
  }
  lines.push('}');
  return lines.join('\n').trimEnd();
}

function exportTailwindConfig(tokens: DesignTokens): string {
  const lines: string[] = [];
  lines.push('// Auto-generated Tailwind config from surplan design tokens');
  lines.push('export default {');
  lines.push('  theme: {');
  lines.push('    extend: {');
  if (tokens.colors.length > 0) {
    lines.push('      colors: {');
    for (const c of tokens.colors) if (c.name) lines.push(`        '${c.name}': '${c.value}',`);
    lines.push('      },');
  }
  if (tokens.typography.length > 0) {
    lines.push('      fontSize: {');
    for (const t of tokens.typography) if (t.name) lines.push(`        '${t.name}': ['${t.fontSize}', { lineHeight: '${t.lineHeight}', letterSpacing: '${t.letterSpacing}', fontWeight: '${t.fontWeight}' }],`);
    lines.push('      },');
  }
  if (tokens.spacing.length > 0) {
    lines.push('      spacing: {');
    for (const s of tokens.spacing) if (s.name) lines.push(`        '${s.name}': '${s.value}',`);
    lines.push('      },');
  }
  if (tokens.breakpoints.length > 0) {
    lines.push('      screens: {');
    for (const b of tokens.breakpoints) if (b.name) lines.push(`        '${b.name}': '${b.value}',`);
    lines.push('      },');
  }
  lines.push('    },');
  lines.push('  },');
  lines.push('};');
  return lines.join('\n').trimEnd();
}

function exportComponentDocs(components: UIComponent[], pages: Page[]): string {
  const lines: string[] = [];
  lines.push('# Frontend Architecture');
  lines.push('');
  lines.push(`> ${pages.length} pages · ${components.length} components`);
  lines.push('');
  if (pages.length > 0) {
    lines.push('## Pages');
    lines.push('');
    lines.push('| Page | Path | Layout | Auth | Status |');
    lines.push('|------|------|--------|------|--------|');
    for (const p of pages) lines.push(`| ${p.name} | \`${p.path}\` | ${p.layout} | ${p.authRequired ? 'Yes' : 'No'} | ${p.status} |`);
    lines.push('');
  }
  if (components.length > 0) {
    lines.push('## Components');
    lines.push('');
    for (const c of components) {
      lines.push(`### \`<${c.name} />\` (${c.kind})`);
      if (c.description) lines.push(`\n${c.description}`);
      lines.push('');
      if (c.props.length > 0) {
        lines.push('| Prop | Type | Required | Default |');
        lines.push('|------|------|----------|---------|');
        for (const p of c.props) lines.push(`| \`${p.name}\` | \`${p.type}\` | ${p.required ? 'Yes' : 'No'} | ${p.defaultValue || '—'} |`);
        lines.push('');
      }
      if (c.events.length > 0) {
        for (const ev of c.events) lines.push(`- **Event:** \`${ev.name}(${ev.payload})\`${ev.description ? ` — ${ev.description}` : ''}`);
        lines.push('');
      }
      if (c.stateFields.length > 0) {
        for (const sf of c.stateFields) lines.push(`- **State:** \`${sf.name}: ${sf.type}\` = \`${sf.initialValue || '—'}\``);
        lines.push('');
      }
    }
  }
  return lines.join('\n').trimEnd() || '# Frontend Architecture\n\nNo pages or components defined.';
}

function exportMermaidSitemap(pages: Page[]): string {
  if (pages.length === 0) return 'graph TD\n  empty["No pages defined"]';
  const lines: string[] = ['graph TD'];
  const idMap: Record<string, string> = {};
  pages.forEach((p, i) => {
    const sid = `P${i}`;
    idMap[p.id] = sid;
    const label = `${p.name}`;
    lines.push(p.authRequired ? `  ${sid}[["${label}<br/>${p.path}"]]` : `  ${sid}["${label}<br/>${p.path}"]`);
  });
  for (const page of pages) {
    for (const tid of page.navigatesTo) {
      if (idMap[page.id] && idMap[tid]) lines.push(`  ${idMap[page.id]} --> ${idMap[tid]}`);
    }
  }
  return lines.join('\n').trimEnd();
}
